// Generated by delombok at Sat Jun 27 10:20:26 GMT 2026
package com.onmm.backend.service.impl.Admin;

import com.onmm.backend.dto.Admin.DashboardStatsResponse;
import com.onmm.backend.entity.DemandeAdhesion;
import com.onmm.backend.entity.enums.ApplicationStatus;
import com.onmm.backend.entity.enums.ReclamationStatus;
import com.onmm.backend.entity.enums.StatutMedecin;
import com.onmm.backend.repository.DemandeAdhesionRepository;
import com.onmm.backend.repository.MedecinRepository;
import com.onmm.backend.repository.ReclamationRepository;
import com.onmm.backend.repository.SpecialiteRepository;
import com.onmm.backend.service.Admin.AdminDashboardService;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.List;

@Service
@Transactional(readOnly = true)
public class AdminDashboardServiceImpl implements AdminDashboardService {
    private final DemandeAdhesionRepository demandeRepo;
    private final MedecinRepository medecinRepo;
    private final ReclamationRepository reclamationRepo;
    private final SpecialiteRepository specialiteRepo;

    @Override
    public DashboardStatsResponse getStats() {
        long totalDemandes = demandeRepo.count();
        long enAttente = demandeRepo.countByStatut(ApplicationStatus.PENDING);
        long acceptees = demandeRepo.countByStatut(ApplicationStatus.APPROUVED);
        long rejetees = demandeRepo.countByStatut(ApplicationStatus.REJECTED);
        long totalMedecins = medecinRepo.count();
        long actifs = medecinRepo.countByStatut(StatutMedecin.ACTIF);
        long suspendus = medecinRepo.countByStatut(StatutMedecin.SUSPENDU);
        long hommes = medecinRepo.countBySexe("Homme");
        long femmes = medecinRepo.countBySexe("Femme");
        long mauritaniens = medecinRepo.countByNationaliteIgnoreCase("mauritanienne");
        long etrangers = totalMedecins - mauritaniens;
        long totalSpecialites = specialiteRepo.count();
        long specialitesAvecMedecins = specialiteRepo.countSpecialitesAvecMedecins();
        long reclamationsEnAttente = reclamationRepo.countByStatut(ReclamationStatus.SUBMITTED) + reclamationRepo.countByStatut(ReclamationStatus.IN_PROGRESS);
        List<DemandeAdhesion> recent = demandeRepo.findTop5ByOrderBySubmissionDateDesc();
        List<DashboardStatsResponse.RecentDemandeDto> recentDtos = recent.stream().map(d -> new DashboardStatsResponse.RecentDemandeDto(d.getId(), d.getNom(), d.getPrenom(), d.getNumeroDossier(), d.getStatut() != null ? d.getStatut().name() : null, d.getSubmissionDate())).toList();
        return new DashboardStatsResponse(totalDemandes, enAttente, acceptees, rejetees, totalMedecins, actifs, suspendus, hommes, femmes, mauritaniens, etrangers, totalSpecialites, specialitesAvecMedecins, reclamationsEnAttente, recentDtos);
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AdminDashboardServiceImpl(final DemandeAdhesionRepository demandeRepo, final MedecinRepository medecinRepo, final ReclamationRepository reclamationRepo, final SpecialiteRepository specialiteRepo) {
        this.demandeRepo = demandeRepo;
        this.medecinRepo = medecinRepo;
        this.reclamationRepo = reclamationRepo;
        this.specialiteRepo = specialiteRepo;
    }
}
