// Generated by delombok at Sat Jun 27 10:20:24 GMT 2026
package com.onmm.backend.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * Admin entity — hérite de User (id, email, password, role, enabled).
 * Les champs ci-dessous vont dans la table `admins` (colonne user_id = FK vers users).
 */
@Entity
@Table(name = "admins")
@PrimaryKeyJoinColumn(name = "user_id")
public class Admin extends User {
    @Column(length = 200)
    private String nomComplet;
    @Column(length = 30)
    private String telephone;
    @Column(name = "photo_profil_path", length = 500)
    private String photoProfilPath;
    @Column(name = "date_creation")
    private LocalDateTime dateCreation;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNomComplet() {
        return this.nomComplet;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTelephone() {
        return this.telephone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPhotoProfilPath() {
        return this.photoProfilPath;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getDateCreation() {
        return this.dateCreation;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNomComplet(final String nomComplet) {
        this.nomComplet = nomComplet;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTelephone(final String telephone) {
        this.telephone = telephone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPhotoProfilPath(final String photoProfilPath) {
        this.photoProfilPath = photoProfilPath;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDateCreation(final LocalDateTime dateCreation) {
        this.dateCreation = dateCreation;
    }
}
