// Generated by delombok at Sat Jun 27 10:20:24 GMT 2026
package com.onmm.backend.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "categorie_contenu")
public class CategorieContenu {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String nom;
    private boolean active = true;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNom() {
        return this.nom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isActive() {
        return this.active;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNom(final String nom) {
        this.nom = nom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setActive(final boolean active) {
        this.active = active;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CategorieContenu() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CategorieContenu(final Long id, final String nom, final boolean active) {
        this.id = id;
        this.nom = nom;
        this.active = active;
    }
}
