// Generated by delombok at Sat Jun 27 10:20:24 GMT 2026
package com.onmm.backend.entity;

import com.onmm.backend.entity.enums.ContenuStatut;
import com.onmm.backend.entity.enums.ContenuType;
import com.onmm.backend.entity.enums.ContenuVisibilite;
import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
public class Contenu {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(length = 180, nullable = false)
    private String titre;
    @Column(columnDefinition = "TEXT", nullable = false)
    private String contenu;
    @Enumerated(EnumType.STRING)
    private ContenuType type;
    @Enumerated(EnumType.STRING)
    private ContenuStatut statut;
    @Enumerated(EnumType.STRING)
    private ContenuVisibilite visibilite;
    @Column(length = 500)
    private String imageUrl;
    @Column(length = 500)
    private String resume;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "categorie_id")
    private CategorieContenu categorie;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by")
    private User createdBy;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "specialite_cible_id")
    private Specialite specialiteCible;
    private LocalDateTime dateCreation;
    private LocalDateTime datePublication;
    private LocalDateTime dateExpiration;


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class ContenuBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String titre;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String contenu;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private ContenuType type;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private ContenuStatut statut;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private ContenuVisibilite visibilite;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String imageUrl;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String resume;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private CategorieContenu categorie;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private User createdBy;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Specialite specialiteCible;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private LocalDateTime dateCreation;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private LocalDateTime datePublication;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private LocalDateTime dateExpiration;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        ContenuBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Contenu.ContenuBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Contenu.ContenuBuilder titre(final String titre) {
            this.titre = titre;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Contenu.ContenuBuilder contenu(final String contenu) {
            this.contenu = contenu;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Contenu.ContenuBuilder type(final ContenuType type) {
            this.type = type;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Contenu.ContenuBuilder statut(final ContenuStatut statut) {
            this.statut = statut;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Contenu.ContenuBuilder visibilite(final ContenuVisibilite visibilite) {
            this.visibilite = visibilite;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Contenu.ContenuBuilder imageUrl(final String imageUrl) {
            this.imageUrl = imageUrl;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Contenu.ContenuBuilder resume(final String resume) {
            this.resume = resume;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Contenu.ContenuBuilder categorie(final CategorieContenu categorie) {
            this.categorie = categorie;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Contenu.ContenuBuilder createdBy(final User createdBy) {
            this.createdBy = createdBy;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Contenu.ContenuBuilder specialiteCible(final Specialite specialiteCible) {
            this.specialiteCible = specialiteCible;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Contenu.ContenuBuilder dateCreation(final LocalDateTime dateCreation) {
            this.dateCreation = dateCreation;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Contenu.ContenuBuilder datePublication(final LocalDateTime datePublication) {
            this.datePublication = datePublication;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Contenu.ContenuBuilder dateExpiration(final LocalDateTime dateExpiration) {
            this.dateExpiration = dateExpiration;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Contenu build() {
            return new Contenu(this.id, this.titre, this.contenu, this.type, this.statut, this.visibilite, this.imageUrl, this.resume, this.categorie, this.createdBy, this.specialiteCible, this.dateCreation, this.datePublication, this.dateExpiration);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "Contenu.ContenuBuilder(id=" + this.id + ", titre=" + this.titre + ", contenu=" + this.contenu + ", type=" + this.type + ", statut=" + this.statut + ", visibilite=" + this.visibilite + ", imageUrl=" + this.imageUrl + ", resume=" + this.resume + ", categorie=" + this.categorie + ", createdBy=" + this.createdBy + ", specialiteCible=" + this.specialiteCible + ", dateCreation=" + this.dateCreation + ", datePublication=" + this.datePublication + ", dateExpiration=" + this.dateExpiration + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static Contenu.ContenuBuilder builder() {
        return new Contenu.ContenuBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTitre() {
        return this.titre;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getContenu() {
        return this.contenu;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ContenuType getType() {
        return this.type;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ContenuStatut getStatut() {
        return this.statut;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ContenuVisibilite getVisibilite() {
        return this.visibilite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getImageUrl() {
        return this.imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getResume() {
        return this.resume;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CategorieContenu getCategorie() {
        return this.categorie;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public User getCreatedBy() {
        return this.createdBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Specialite getSpecialiteCible() {
        return this.specialiteCible;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getDateCreation() {
        return this.dateCreation;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getDatePublication() {
        return this.datePublication;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getDateExpiration() {
        return this.dateExpiration;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTitre(final String titre) {
        this.titre = titre;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setContenu(final String contenu) {
        this.contenu = contenu;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setType(final ContenuType type) {
        this.type = type;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatut(final ContenuStatut statut) {
        this.statut = statut;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVisibilite(final ContenuVisibilite visibilite) {
        this.visibilite = visibilite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setImageUrl(final String imageUrl) {
        this.imageUrl = imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setResume(final String resume) {
        this.resume = resume;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategorie(final CategorieContenu categorie) {
        this.categorie = categorie;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedBy(final User createdBy) {
        this.createdBy = createdBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSpecialiteCible(final Specialite specialiteCible) {
        this.specialiteCible = specialiteCible;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDateCreation(final LocalDateTime dateCreation) {
        this.dateCreation = dateCreation;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDatePublication(final LocalDateTime datePublication) {
        this.datePublication = datePublication;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDateExpiration(final LocalDateTime dateExpiration) {
        this.dateExpiration = dateExpiration;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Contenu)) return false;
        final Contenu other = (Contenu) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$titre = this.getTitre();
        final java.lang.Object other$titre = other.getTitre();
        if (this$titre == null ? other$titre != null : !this$titre.equals(other$titre)) return false;
        final java.lang.Object this$contenu = this.getContenu();
        final java.lang.Object other$contenu = other.getContenu();
        if (this$contenu == null ? other$contenu != null : !this$contenu.equals(other$contenu)) return false;
        final java.lang.Object this$type = this.getType();
        final java.lang.Object other$type = other.getType();
        if (this$type == null ? other$type != null : !this$type.equals(other$type)) return false;
        final java.lang.Object this$statut = this.getStatut();
        final java.lang.Object other$statut = other.getStatut();
        if (this$statut == null ? other$statut != null : !this$statut.equals(other$statut)) return false;
        final java.lang.Object this$visibilite = this.getVisibilite();
        final java.lang.Object other$visibilite = other.getVisibilite();
        if (this$visibilite == null ? other$visibilite != null : !this$visibilite.equals(other$visibilite)) return false;
        final java.lang.Object this$imageUrl = this.getImageUrl();
        final java.lang.Object other$imageUrl = other.getImageUrl();
        if (this$imageUrl == null ? other$imageUrl != null : !this$imageUrl.equals(other$imageUrl)) return false;
        final java.lang.Object this$resume = this.getResume();
        final java.lang.Object other$resume = other.getResume();
        if (this$resume == null ? other$resume != null : !this$resume.equals(other$resume)) return false;
        final java.lang.Object this$categorie = this.getCategorie();
        final java.lang.Object other$categorie = other.getCategorie();
        if (this$categorie == null ? other$categorie != null : !this$categorie.equals(other$categorie)) return false;
        final java.lang.Object this$createdBy = this.getCreatedBy();
        final java.lang.Object other$createdBy = other.getCreatedBy();
        if (this$createdBy == null ? other$createdBy != null : !this$createdBy.equals(other$createdBy)) return false;
        final java.lang.Object this$specialiteCible = this.getSpecialiteCible();
        final java.lang.Object other$specialiteCible = other.getSpecialiteCible();
        if (this$specialiteCible == null ? other$specialiteCible != null : !this$specialiteCible.equals(other$specialiteCible)) return false;
        final java.lang.Object this$dateCreation = this.getDateCreation();
        final java.lang.Object other$dateCreation = other.getDateCreation();
        if (this$dateCreation == null ? other$dateCreation != null : !this$dateCreation.equals(other$dateCreation)) return false;
        final java.lang.Object this$datePublication = this.getDatePublication();
        final java.lang.Object other$datePublication = other.getDatePublication();
        if (this$datePublication == null ? other$datePublication != null : !this$datePublication.equals(other$datePublication)) return false;
        final java.lang.Object this$dateExpiration = this.getDateExpiration();
        final java.lang.Object other$dateExpiration = other.getDateExpiration();
        if (this$dateExpiration == null ? other$dateExpiration != null : !this$dateExpiration.equals(other$dateExpiration)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Contenu;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $titre = this.getTitre();
        result = result * PRIME + ($titre == null ? 43 : $titre.hashCode());
        final java.lang.Object $contenu = this.getContenu();
        result = result * PRIME + ($contenu == null ? 43 : $contenu.hashCode());
        final java.lang.Object $type = this.getType();
        result = result * PRIME + ($type == null ? 43 : $type.hashCode());
        final java.lang.Object $statut = this.getStatut();
        result = result * PRIME + ($statut == null ? 43 : $statut.hashCode());
        final java.lang.Object $visibilite = this.getVisibilite();
        result = result * PRIME + ($visibilite == null ? 43 : $visibilite.hashCode());
        final java.lang.Object $imageUrl = this.getImageUrl();
        result = result * PRIME + ($imageUrl == null ? 43 : $imageUrl.hashCode());
        final java.lang.Object $resume = this.getResume();
        result = result * PRIME + ($resume == null ? 43 : $resume.hashCode());
        final java.lang.Object $categorie = this.getCategorie();
        result = result * PRIME + ($categorie == null ? 43 : $categorie.hashCode());
        final java.lang.Object $createdBy = this.getCreatedBy();
        result = result * PRIME + ($createdBy == null ? 43 : $createdBy.hashCode());
        final java.lang.Object $specialiteCible = this.getSpecialiteCible();
        result = result * PRIME + ($specialiteCible == null ? 43 : $specialiteCible.hashCode());
        final java.lang.Object $dateCreation = this.getDateCreation();
        result = result * PRIME + ($dateCreation == null ? 43 : $dateCreation.hashCode());
        final java.lang.Object $datePublication = this.getDatePublication();
        result = result * PRIME + ($datePublication == null ? 43 : $datePublication.hashCode());
        final java.lang.Object $dateExpiration = this.getDateExpiration();
        result = result * PRIME + ($dateExpiration == null ? 43 : $dateExpiration.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "Contenu(id=" + this.getId() + ", titre=" + this.getTitre() + ", contenu=" + this.getContenu() + ", type=" + this.getType() + ", statut=" + this.getStatut() + ", visibilite=" + this.getVisibilite() + ", imageUrl=" + this.getImageUrl() + ", resume=" + this.getResume() + ", categorie=" + this.getCategorie() + ", createdBy=" + this.getCreatedBy() + ", specialiteCible=" + this.getSpecialiteCible() + ", dateCreation=" + this.getDateCreation() + ", datePublication=" + this.getDatePublication() + ", dateExpiration=" + this.getDateExpiration() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Contenu() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Contenu(final Long id, final String titre, final String contenu, final ContenuType type, final ContenuStatut statut, final ContenuVisibilite visibilite, final String imageUrl, final String resume, final CategorieContenu categorie, final User createdBy, final Specialite specialiteCible, final LocalDateTime dateCreation, final LocalDateTime datePublication, final LocalDateTime dateExpiration) {
        this.id = id;
        this.titre = titre;
        this.contenu = contenu;
        this.type = type;
        this.statut = statut;
        this.visibilite = visibilite;
        this.imageUrl = imageUrl;
        this.resume = resume;
        this.categorie = categorie;
        this.createdBy = createdBy;
        this.specialiteCible = specialiteCible;
        this.dateCreation = dateCreation;
        this.datePublication = datePublication;
        this.dateExpiration = dateExpiration;
    }
}
