// Generated by delombok at Sat Jun 27 10:20:24 GMT 2026
package com.onmm.backend.entity;

import com.onmm.backend.entity.enums.ApplicationStatus;
import jakarta.persistence.*;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

@Entity
@Table(name = "demande_adhesion")
public class DemandeAdhesion {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private String NNI;
    @Column(nullable = false)
    private String nom;
    @Column(nullable = false)
    private String prenom;
    @Column(nullable = false)
    private String sexe;
    @Column(nullable = false)
    private String nationalite;
    @Column(nullable = false)
    private LocalDate dateNaissance;
    @Column(nullable = false)
    private String email;
    @Column(nullable = false)
    private String telephone;
    @Column(nullable = false)
    private String adresse;
    @Column(name = "wilaya_exercice", length = 100)
    private String wilayaExercice;
    @Column(name = "est_enseignant_chercheur", nullable = false, columnDefinition = "BOOLEAN NOT NULL DEFAULT FALSE")
    private boolean estEnseignantChercheur = false;
    private String numeroDossier;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ApplicationStatus statut;
    @Column(nullable = false)
    private LocalDateTime submissionDate;
    @Column(nullable = true)
    private LocalDateTime decisionDate;
    @Column(length = 1000)
    private String adminComment;
    @OneToMany(mappedBy = "demandeAdhesion", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    private Set<DemandeEducation> educations;
    @OneToMany(mappedBy = "demandeAdhesion", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    private Set<DemandeExperience> experiences;
    @OneToMany(mappedBy = "demandeAdhesion", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    private Set<DemandeDocument> documents;

    public DemandeAdhesion() {
    }

    public boolean isPending() {
        return this.statut == ApplicationStatus.PENDING;
    }

    public boolean isApproved() {
        return this.statut == ApplicationStatus.APPROUVED;
    }

    public boolean isRejected() {
        return this.statut == ApplicationStatus.REJECTED;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNNI() {
        return this.NNI;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNom() {
        return this.nom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPrenom() {
        return this.prenom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSexe() {
        return this.sexe;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNationalite() {
        return this.nationalite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDate getDateNaissance() {
        return this.dateNaissance;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTelephone() {
        return this.telephone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAdresse() {
        return this.adresse;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getWilayaExercice() {
        return this.wilayaExercice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isEstEnseignantChercheur() {
        return this.estEnseignantChercheur;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNumeroDossier() {
        return this.numeroDossier;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ApplicationStatus getStatut() {
        return this.statut;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getSubmissionDate() {
        return this.submissionDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getDecisionDate() {
        return this.decisionDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAdminComment() {
        return this.adminComment;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Set<DemandeEducation> getEducations() {
        return this.educations;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Set<DemandeExperience> getExperiences() {
        return this.experiences;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Set<DemandeDocument> getDocuments() {
        return this.documents;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNNI(final String NNI) {
        this.NNI = NNI;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNom(final String nom) {
        this.nom = nom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPrenom(final String prenom) {
        this.prenom = prenom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSexe(final String sexe) {
        this.sexe = sexe;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNationalite(final String nationalite) {
        this.nationalite = nationalite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDateNaissance(final LocalDate dateNaissance) {
        this.dateNaissance = dateNaissance;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTelephone(final String telephone) {
        this.telephone = telephone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAdresse(final String adresse) {
        this.adresse = adresse;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWilayaExercice(final String wilayaExercice) {
        this.wilayaExercice = wilayaExercice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEstEnseignantChercheur(final boolean estEnseignantChercheur) {
        this.estEnseignantChercheur = estEnseignantChercheur;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNumeroDossier(final String numeroDossier) {
        this.numeroDossier = numeroDossier;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatut(final ApplicationStatus statut) {
        this.statut = statut;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSubmissionDate(final LocalDateTime submissionDate) {
        this.submissionDate = submissionDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDecisionDate(final LocalDateTime decisionDate) {
        this.decisionDate = decisionDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAdminComment(final String adminComment) {
        this.adminComment = adminComment;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEducations(final Set<DemandeEducation> educations) {
        this.educations = educations;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setExperiences(final Set<DemandeExperience> experiences) {
        this.experiences = experiences;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDocuments(final Set<DemandeDocument> documents) {
        this.documents = documents;
    }
}
