// Generated by delombok at Sat Jun 27 10:20:24 GMT 2026
package com.onmm.backend.entity;

import jakarta.persistence.*;
import java.time.LocalDate;

@Entity
@Table(name = "medecin_experience")
public class MedecinExperience {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    // Chaque expérience appartient à un seul médecin
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "medecin_id", nullable = false)
    private Medecin medecin;
    @Column(name = "nom_etablissement", nullable = false)
    private String nomEtablissement;
    @Column(nullable = false)
    private String poste;
    @Column(nullable = false)
    private String pays;
    @Column(nullable = false)
    private String ville;
    @Column(name = "date_debut", nullable = false)
    private LocalDate dateDebut;
    @Column(name = "date_fin")
    private LocalDate dateFin;
    @Column(nullable = false)
    private String description;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Medecin getMedecin() {
        return this.medecin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNomEtablissement() {
        return this.nomEtablissement;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPoste() {
        return this.poste;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPays() {
        return this.pays;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getVille() {
        return this.ville;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDate getDateDebut() {
        return this.dateDebut;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDate getDateFin() {
        return this.dateFin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMedecin(final Medecin medecin) {
        this.medecin = medecin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNomEtablissement(final String nomEtablissement) {
        this.nomEtablissement = nomEtablissement;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPoste(final String poste) {
        this.poste = poste;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPays(final String pays) {
        this.pays = pays;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVille(final String ville) {
        this.ville = ville;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDateDebut(final LocalDate dateDebut) {
        this.dateDebut = dateDebut;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDateFin(final LocalDate dateFin) {
        this.dateFin = dateFin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDescription(final String description) {
        this.description = description;
    }
}
