// Generated by delombok at Sat Jun 27 10:20:24 GMT 2026
package com.onmm.backend.entity;

import com.onmm.backend.entity.enums.SectionOrdre;
import com.onmm.backend.entity.enums.StatutMedecin;
import jakarta.persistence.*;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "medecins",
        uniqueConstraints = {
            @UniqueConstraint(name = "uk_medecin_telephone", columnNames = "telephone"),
            @UniqueConstraint(name = "uk_medecin_nni", columnNames = "nni"),
            @UniqueConstraint(name = "uk_medecin_numero_inscription", columnNames = "numero_inscription")
        },
        indexes = {
            @Index(name = "idx_medecin_statut",      columnList = "statut"),
            @Index(name = "idx_medecin_sexe",        columnList = "sexe"),
            @Index(name = "idx_medecin_nationalite", columnList = "nationalite")
        })
@PrimaryKeyJoinColumn(name = "user_id")
public class Medecin extends User {
    @Column(nullable = false, length = 100)
    private String nom;
    @Column(nullable = false, length = 100)
    private String prenom;
    @Column(nullable = false, unique = true, length = 30)
    private String telephone;
    @Column(nullable = false, unique = true, length = 30)
    private String nni;
    @Column(name = "photo_profil_path", length = 500)
    private String photoProfilPath;
    @Column(length = 20)
    private String sexe;
    @Column(length = 100)
    private String nationalite;
    @Column(length = 255)
    private String adresse;
    @Column(name = "numero_inscription", unique = true, length = 100)
    private String numeroInscription;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private StatutMedecin statut;
    @Column(name = "commentaire_suspension", length = 1000)
    private String commentaireSuspension;
    @Enumerated(EnumType.STRING)
    @Column(name = "section_ordre", nullable = false, length = 50)
    private SectionOrdre sectionOrdre;
    @Column(name = "date_naissance")
    private LocalDate dateNaissance;
    @Column(name = "date_approuvement")
    private LocalDate dateApprouvement;
    @Column(name = "ville_exercice", length = 100)
    private String villeExercice;
    @Column(name = "wilaya_exercice", length = 100)
    private String wilayaExercice;
    @Column(name = "structure_exercice", length = 100)
    private String structureExercice;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "demande_id")
    private DemandeAdhesion demandeOrigine;
    @OneToMany(mappedBy = "medecin", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<MedecinEducation> educations = new ArrayList<>();
    @OneToMany(mappedBy = "medecin", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<MedecinExperience> experiences = new ArrayList<>();
    @OneToMany(mappedBy = "medecin", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<MedecinDocument> documents = new ArrayList<>();

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNom() {
        return this.nom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPrenom() {
        return this.prenom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTelephone() {
        return this.telephone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNni() {
        return this.nni;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPhotoProfilPath() {
        return this.photoProfilPath;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSexe() {
        return this.sexe;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNationalite() {
        return this.nationalite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAdresse() {
        return this.adresse;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNumeroInscription() {
        return this.numeroInscription;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public StatutMedecin getStatut() {
        return this.statut;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCommentaireSuspension() {
        return this.commentaireSuspension;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public SectionOrdre getSectionOrdre() {
        return this.sectionOrdre;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDate getDateNaissance() {
        return this.dateNaissance;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDate getDateApprouvement() {
        return this.dateApprouvement;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getVilleExercice() {
        return this.villeExercice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getWilayaExercice() {
        return this.wilayaExercice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStructureExercice() {
        return this.structureExercice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DemandeAdhesion getDemandeOrigine() {
        return this.demandeOrigine;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<MedecinEducation> getEducations() {
        return this.educations;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<MedecinExperience> getExperiences() {
        return this.experiences;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<MedecinDocument> getDocuments() {
        return this.documents;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNom(final String nom) {
        this.nom = nom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPrenom(final String prenom) {
        this.prenom = prenom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTelephone(final String telephone) {
        this.telephone = telephone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNni(final String nni) {
        this.nni = nni;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPhotoProfilPath(final String photoProfilPath) {
        this.photoProfilPath = photoProfilPath;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSexe(final String sexe) {
        this.sexe = sexe;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNationalite(final String nationalite) {
        this.nationalite = nationalite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAdresse(final String adresse) {
        this.adresse = adresse;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNumeroInscription(final String numeroInscription) {
        this.numeroInscription = numeroInscription;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatut(final StatutMedecin statut) {
        this.statut = statut;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCommentaireSuspension(final String commentaireSuspension) {
        this.commentaireSuspension = commentaireSuspension;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSectionOrdre(final SectionOrdre sectionOrdre) {
        this.sectionOrdre = sectionOrdre;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDateNaissance(final LocalDate dateNaissance) {
        this.dateNaissance = dateNaissance;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDateApprouvement(final LocalDate dateApprouvement) {
        this.dateApprouvement = dateApprouvement;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVilleExercice(final String villeExercice) {
        this.villeExercice = villeExercice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWilayaExercice(final String wilayaExercice) {
        this.wilayaExercice = wilayaExercice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStructureExercice(final String structureExercice) {
        this.structureExercice = structureExercice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDemandeOrigine(final DemandeAdhesion demandeOrigine) {
        this.demandeOrigine = demandeOrigine;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEducations(final List<MedecinEducation> educations) {
        this.educations = educations;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setExperiences(final List<MedecinExperience> experiences) {
        this.experiences = experiences;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDocuments(final List<MedecinDocument> documents) {
        this.documents = documents;
    }
}
