// Generated by delombok at Sat Jun 27 10:20:24 GMT 2026
package com.onmm.backend.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "medecin_education")
public class MedecinEducation {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    // Chaque formation appartient à un seul médecin
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "medecin_id", nullable = false)
    private Medecin medecin;
    @Column(nullable = false, length = 150)
    private String diplome;
    @Column(nullable = false, length = 150)
    private String universite;
    @Column(nullable = false, length = 100)
    private String pays;
    @Column(nullable = false, length = 100)
    private String ville;
    @Column(name = "annee_obtention", nullable = false)
    private Integer anneeObtention;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "specialite_id")
    private Specialite specialite;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sous_specialite_id")
    private SousSpecialite sousSpecialite;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Medecin getMedecin() {
        return this.medecin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDiplome() {
        return this.diplome;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getUniversite() {
        return this.universite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPays() {
        return this.pays;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getVille() {
        return this.ville;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getAnneeObtention() {
        return this.anneeObtention;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Specialite getSpecialite() {
        return this.specialite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public SousSpecialite getSousSpecialite() {
        return this.sousSpecialite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMedecin(final Medecin medecin) {
        this.medecin = medecin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDiplome(final String diplome) {
        this.diplome = diplome;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUniversite(final String universite) {
        this.universite = universite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPays(final String pays) {
        this.pays = pays;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVille(final String ville) {
        this.ville = ville;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAnneeObtention(final Integer anneeObtention) {
        this.anneeObtention = anneeObtention;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSpecialite(final Specialite specialite) {
        this.specialite = specialite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSousSpecialite(final SousSpecialite sousSpecialite) {
        this.sousSpecialite = sousSpecialite;
    }
}
