// Generated by delombok at Sat Jun 27 10:20:24 GMT 2026
package com.onmm.backend.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "medecin_document")
public class MedecinDocument {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    // Chaque document appartient à un seul médecin
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "medecin_id", nullable = false)
    private Medecin medecin;
    @Column(name = "file_name", nullable = false)
    private String fileName;
    @Column(name = "file_path", nullable = false)
    private String filePath;
    @Column(name = "type_document", nullable = false)
    private String typeDocument;
    @Column(nullable = false)
    private String categorie;
    @Column(nullable = false)
    private Long size;
    @Column(name = "upload_date", nullable = false)
    private LocalDateTime uploadDate;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Medecin getMedecin() {
        return this.medecin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFileName() {
        return this.fileName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFilePath() {
        return this.filePath;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTypeDocument() {
        return this.typeDocument;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCategorie() {
        return this.categorie;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getSize() {
        return this.size;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getUploadDate() {
        return this.uploadDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMedecin(final Medecin medecin) {
        this.medecin = medecin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFileName(final String fileName) {
        this.fileName = fileName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFilePath(final String filePath) {
        this.filePath = filePath;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTypeDocument(final String typeDocument) {
        this.typeDocument = typeDocument;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategorie(final String categorie) {
        this.categorie = categorie;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSize(final Long size) {
        this.size = size;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUploadDate(final LocalDateTime uploadDate) {
        this.uploadDate = uploadDate;
    }
}
