// Generated by delombok at Sat Jun 27 10:20:25 GMT 2026
package com.onmm.backend.entity;

import com.onmm.backend.entity.enums.ReclamationAuteurType;
import com.onmm.backend.entity.enums.ReclamationCategory;
import com.onmm.backend.entity.enums.ReclamationModule;
import com.onmm.backend.entity.enums.ReclamationPriorite;
import com.onmm.backend.entity.enums.ReclamationStatus;
import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "reclamations",
        indexes = {
            @Index(name = "idx_reclamation_statut", columnList = "statut")
        })
public class Reclamation {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "numero_reclamation", nullable = false, unique = true)
    private String numeroReclamation;
    @Enumerated(EnumType.STRING)
    @Column(name = "type_auteur", nullable = false)
    private ReclamationAuteurType typeAuteur;
    @Enumerated(EnumType.STRING)
    @Column(name = "categorie", nullable = false)
    private ReclamationCategory categorie;
    @Enumerated(EnumType.STRING)
    @Column(name = "priorite", nullable = false)
    private ReclamationPriorite priorite;
    @Enumerated(EnumType.STRING)
    @Column(name = "module_concerne", nullable = false)
    private ReclamationModule moduleConcerne;
    @Column(nullable = false)
    private String objet;
    @Column(nullable = false, columnDefinition = "TEXT")
    private String message;
    @Column(name = "piece_jointe_path")
    private String pieceJointePath;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ReclamationStatus statut;
    @Column(name = "date_creation", nullable = false)
    private LocalDateTime dateCreation;
    @Column(name = "date_prise_en_charge")
    private LocalDateTime datePriseEnCharge;
    @Column(name = "date_cloture")
    private LocalDateTime dateCloture;
    @Column(name = "date_derniere_mise_a_jour")
    private LocalDateTime dateDerniereMiseAJour;
    // Cas médecin
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "medecin_id")
    private Medecin medecin;
    // Cas citoyen
    @Column(name = "nom_citoyen")
    private String nomCitoyen;
    @Column(name = "prenom_citoyen")
    private String prenomCitoyen;
    @Column(name = "ville_citoyen")
    private String villeCitoyen;
    @Column(name = "adresse_citoyen")
    private String adresseCitoyen;
    @Column(name = "telephone_citoyen")
    private String telephoneCitoyen;
    @Column(name = "email_citoyen")
    private String emailCitoyen;
    // Traitement admin
    @Column(name = "admin_response", columnDefinition = "TEXT")
    private String adminResponse;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "admin_id")
    private User adminTraiteur;

    public Reclamation() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNumeroReclamation() {
        return this.numeroReclamation;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ReclamationAuteurType getTypeAuteur() {
        return this.typeAuteur;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ReclamationCategory getCategorie() {
        return this.categorie;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ReclamationPriorite getPriorite() {
        return this.priorite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ReclamationModule getModuleConcerne() {
        return this.moduleConcerne;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getObjet() {
        return this.objet;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getMessage() {
        return this.message;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPieceJointePath() {
        return this.pieceJointePath;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ReclamationStatus getStatut() {
        return this.statut;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getDateCreation() {
        return this.dateCreation;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getDatePriseEnCharge() {
        return this.datePriseEnCharge;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getDateCloture() {
        return this.dateCloture;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getDateDerniereMiseAJour() {
        return this.dateDerniereMiseAJour;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Medecin getMedecin() {
        return this.medecin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNomCitoyen() {
        return this.nomCitoyen;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPrenomCitoyen() {
        return this.prenomCitoyen;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getVilleCitoyen() {
        return this.villeCitoyen;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAdresseCitoyen() {
        return this.adresseCitoyen;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTelephoneCitoyen() {
        return this.telephoneCitoyen;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEmailCitoyen() {
        return this.emailCitoyen;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAdminResponse() {
        return this.adminResponse;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public User getAdminTraiteur() {
        return this.adminTraiteur;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNumeroReclamation(final String numeroReclamation) {
        this.numeroReclamation = numeroReclamation;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTypeAuteur(final ReclamationAuteurType typeAuteur) {
        this.typeAuteur = typeAuteur;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategorie(final ReclamationCategory categorie) {
        this.categorie = categorie;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPriorite(final ReclamationPriorite priorite) {
        this.priorite = priorite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setModuleConcerne(final ReclamationModule moduleConcerne) {
        this.moduleConcerne = moduleConcerne;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setObjet(final String objet) {
        this.objet = objet;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMessage(final String message) {
        this.message = message;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPieceJointePath(final String pieceJointePath) {
        this.pieceJointePath = pieceJointePath;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatut(final ReclamationStatus statut) {
        this.statut = statut;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDateCreation(final LocalDateTime dateCreation) {
        this.dateCreation = dateCreation;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDatePriseEnCharge(final LocalDateTime datePriseEnCharge) {
        this.datePriseEnCharge = datePriseEnCharge;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDateCloture(final LocalDateTime dateCloture) {
        this.dateCloture = dateCloture;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDateDerniereMiseAJour(final LocalDateTime dateDerniereMiseAJour) {
        this.dateDerniereMiseAJour = dateDerniereMiseAJour;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMedecin(final Medecin medecin) {
        this.medecin = medecin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNomCitoyen(final String nomCitoyen) {
        this.nomCitoyen = nomCitoyen;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPrenomCitoyen(final String prenomCitoyen) {
        this.prenomCitoyen = prenomCitoyen;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVilleCitoyen(final String villeCitoyen) {
        this.villeCitoyen = villeCitoyen;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAdresseCitoyen(final String adresseCitoyen) {
        this.adresseCitoyen = adresseCitoyen;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTelephoneCitoyen(final String telephoneCitoyen) {
        this.telephoneCitoyen = telephoneCitoyen;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmailCitoyen(final String emailCitoyen) {
        this.emailCitoyen = emailCitoyen;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAdminResponse(final String adminResponse) {
        this.adminResponse = adminResponse;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAdminTraiteur(final User adminTraiteur) {
        this.adminTraiteur = adminTraiteur;
    }
}
