// Generated by delombok at Sat Jun 27 10:20:24 GMT 2026
package com.onmm.backend.dto.medecin;

public class AddMedecinExperienceRequest {
    private String poste;
    private String nomEtablissement;
    private String pays;
    private String ville;
    private String dateDebut;
    private String dateFin;
    private String description;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPoste() {
        return this.poste;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNomEtablissement() {
        return this.nomEtablissement;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPays() {
        return this.pays;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getVille() {
        return this.ville;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDateDebut() {
        return this.dateDebut;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDateFin() {
        return this.dateFin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPoste(final String poste) {
        this.poste = poste;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNomEtablissement(final String nomEtablissement) {
        this.nomEtablissement = nomEtablissement;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPays(final String pays) {
        this.pays = pays;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVille(final String ville) {
        this.ville = ville;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDateDebut(final String dateDebut) {
        this.dateDebut = dateDebut;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDateFin(final String dateFin) {
        this.dateFin = dateFin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDescription(final String description) {
        this.description = description;
    }
}
