// Generated by delombok at Sat Jun 27 10:20:24 GMT 2026
package com.onmm.backend.dto.medecin;

public class AddMedecinEducationRequest {
    private Long specialiteId;
    private Long sousSpecialiteId;
    private String diplome;
    private Integer anneeObtention;
    private String pays;
    private String ville;
    private String universite;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getSpecialiteId() {
        return this.specialiteId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getSousSpecialiteId() {
        return this.sousSpecialiteId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDiplome() {
        return this.diplome;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getAnneeObtention() {
        return this.anneeObtention;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPays() {
        return this.pays;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getVille() {
        return this.ville;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getUniversite() {
        return this.universite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSpecialiteId(final Long specialiteId) {
        this.specialiteId = specialiteId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSousSpecialiteId(final Long sousSpecialiteId) {
        this.sousSpecialiteId = sousSpecialiteId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDiplome(final String diplome) {
        this.diplome = diplome;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAnneeObtention(final Integer anneeObtention) {
        this.anneeObtention = anneeObtention;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPays(final String pays) {
        this.pays = pays;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVille(final String ville) {
        this.ville = ville;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUniversite(final String universite) {
        this.universite = universite;
    }
}
