// Generated by delombok at Sat Jun 27 10:20:24 GMT 2026
package com.onmm.backend.dto.medecin;

import java.util.List;

public class MedecinProfileResponse {
    private Long id;
    private String nom;
    private String prenom;
    private String email;
    private String telephone;
    private String nni;
    private String sexe;
    private String nationalite;
    private String adresse;
    private String numeroInscription;
    private String statut;
    private String photoProfilPath;
    private String sectionOrdre;
    private String villeExercice;
    private String wilayaExercice;
    private List<MedecinEducationDto> educations;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public MedecinProfileResponse() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNom() {
        return this.nom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPrenom() {
        return this.prenom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTelephone() {
        return this.telephone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNni() {
        return this.nni;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSexe() {
        return this.sexe;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNationalite() {
        return this.nationalite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAdresse() {
        return this.adresse;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNumeroInscription() {
        return this.numeroInscription;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatut() {
        return this.statut;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPhotoProfilPath() {
        return this.photoProfilPath;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSectionOrdre() {
        return this.sectionOrdre;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getVilleExercice() {
        return this.villeExercice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getWilayaExercice() {
        return this.wilayaExercice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<MedecinEducationDto> getEducations() {
        return this.educations;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNom(final String nom) {
        this.nom = nom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPrenom(final String prenom) {
        this.prenom = prenom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTelephone(final String telephone) {
        this.telephone = telephone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNni(final String nni) {
        this.nni = nni;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSexe(final String sexe) {
        this.sexe = sexe;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNationalite(final String nationalite) {
        this.nationalite = nationalite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAdresse(final String adresse) {
        this.adresse = adresse;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNumeroInscription(final String numeroInscription) {
        this.numeroInscription = numeroInscription;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatut(final String statut) {
        this.statut = statut;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPhotoProfilPath(final String photoProfilPath) {
        this.photoProfilPath = photoProfilPath;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSectionOrdre(final String sectionOrdre) {
        this.sectionOrdre = sectionOrdre;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVilleExercice(final String villeExercice) {
        this.villeExercice = villeExercice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWilayaExercice(final String wilayaExercice) {
        this.wilayaExercice = wilayaExercice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEducations(final List<MedecinEducationDto> educations) {
        this.educations = educations;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof MedecinProfileResponse)) return false;
        final MedecinProfileResponse other = (MedecinProfileResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$nom = this.getNom();
        final java.lang.Object other$nom = other.getNom();
        if (this$nom == null ? other$nom != null : !this$nom.equals(other$nom)) return false;
        final java.lang.Object this$prenom = this.getPrenom();
        final java.lang.Object other$prenom = other.getPrenom();
        if (this$prenom == null ? other$prenom != null : !this$prenom.equals(other$prenom)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$telephone = this.getTelephone();
        final java.lang.Object other$telephone = other.getTelephone();
        if (this$telephone == null ? other$telephone != null : !this$telephone.equals(other$telephone)) return false;
        final java.lang.Object this$nni = this.getNni();
        final java.lang.Object other$nni = other.getNni();
        if (this$nni == null ? other$nni != null : !this$nni.equals(other$nni)) return false;
        final java.lang.Object this$sexe = this.getSexe();
        final java.lang.Object other$sexe = other.getSexe();
        if (this$sexe == null ? other$sexe != null : !this$sexe.equals(other$sexe)) return false;
        final java.lang.Object this$nationalite = this.getNationalite();
        final java.lang.Object other$nationalite = other.getNationalite();
        if (this$nationalite == null ? other$nationalite != null : !this$nationalite.equals(other$nationalite)) return false;
        final java.lang.Object this$adresse = this.getAdresse();
        final java.lang.Object other$adresse = other.getAdresse();
        if (this$adresse == null ? other$adresse != null : !this$adresse.equals(other$adresse)) return false;
        final java.lang.Object this$numeroInscription = this.getNumeroInscription();
        final java.lang.Object other$numeroInscription = other.getNumeroInscription();
        if (this$numeroInscription == null ? other$numeroInscription != null : !this$numeroInscription.equals(other$numeroInscription)) return false;
        final java.lang.Object this$statut = this.getStatut();
        final java.lang.Object other$statut = other.getStatut();
        if (this$statut == null ? other$statut != null : !this$statut.equals(other$statut)) return false;
        final java.lang.Object this$photoProfilPath = this.getPhotoProfilPath();
        final java.lang.Object other$photoProfilPath = other.getPhotoProfilPath();
        if (this$photoProfilPath == null ? other$photoProfilPath != null : !this$photoProfilPath.equals(other$photoProfilPath)) return false;
        final java.lang.Object this$sectionOrdre = this.getSectionOrdre();
        final java.lang.Object other$sectionOrdre = other.getSectionOrdre();
        if (this$sectionOrdre == null ? other$sectionOrdre != null : !this$sectionOrdre.equals(other$sectionOrdre)) return false;
        final java.lang.Object this$villeExercice = this.getVilleExercice();
        final java.lang.Object other$villeExercice = other.getVilleExercice();
        if (this$villeExercice == null ? other$villeExercice != null : !this$villeExercice.equals(other$villeExercice)) return false;
        final java.lang.Object this$wilayaExercice = this.getWilayaExercice();
        final java.lang.Object other$wilayaExercice = other.getWilayaExercice();
        if (this$wilayaExercice == null ? other$wilayaExercice != null : !this$wilayaExercice.equals(other$wilayaExercice)) return false;
        final java.lang.Object this$educations = this.getEducations();
        final java.lang.Object other$educations = other.getEducations();
        if (this$educations == null ? other$educations != null : !this$educations.equals(other$educations)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof MedecinProfileResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $nom = this.getNom();
        result = result * PRIME + ($nom == null ? 43 : $nom.hashCode());
        final java.lang.Object $prenom = this.getPrenom();
        result = result * PRIME + ($prenom == null ? 43 : $prenom.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $telephone = this.getTelephone();
        result = result * PRIME + ($telephone == null ? 43 : $telephone.hashCode());
        final java.lang.Object $nni = this.getNni();
        result = result * PRIME + ($nni == null ? 43 : $nni.hashCode());
        final java.lang.Object $sexe = this.getSexe();
        result = result * PRIME + ($sexe == null ? 43 : $sexe.hashCode());
        final java.lang.Object $nationalite = this.getNationalite();
        result = result * PRIME + ($nationalite == null ? 43 : $nationalite.hashCode());
        final java.lang.Object $adresse = this.getAdresse();
        result = result * PRIME + ($adresse == null ? 43 : $adresse.hashCode());
        final java.lang.Object $numeroInscription = this.getNumeroInscription();
        result = result * PRIME + ($numeroInscription == null ? 43 : $numeroInscription.hashCode());
        final java.lang.Object $statut = this.getStatut();
        result = result * PRIME + ($statut == null ? 43 : $statut.hashCode());
        final java.lang.Object $photoProfilPath = this.getPhotoProfilPath();
        result = result * PRIME + ($photoProfilPath == null ? 43 : $photoProfilPath.hashCode());
        final java.lang.Object $sectionOrdre = this.getSectionOrdre();
        result = result * PRIME + ($sectionOrdre == null ? 43 : $sectionOrdre.hashCode());
        final java.lang.Object $villeExercice = this.getVilleExercice();
        result = result * PRIME + ($villeExercice == null ? 43 : $villeExercice.hashCode());
        final java.lang.Object $wilayaExercice = this.getWilayaExercice();
        result = result * PRIME + ($wilayaExercice == null ? 43 : $wilayaExercice.hashCode());
        final java.lang.Object $educations = this.getEducations();
        result = result * PRIME + ($educations == null ? 43 : $educations.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "MedecinProfileResponse(id=" + this.getId() + ", nom=" + this.getNom() + ", prenom=" + this.getPrenom() + ", email=" + this.getEmail() + ", telephone=" + this.getTelephone() + ", nni=" + this.getNni() + ", sexe=" + this.getSexe() + ", nationalite=" + this.getNationalite() + ", adresse=" + this.getAdresse() + ", numeroInscription=" + this.getNumeroInscription() + ", statut=" + this.getStatut() + ", photoProfilPath=" + this.getPhotoProfilPath() + ", sectionOrdre=" + this.getSectionOrdre() + ", villeExercice=" + this.getVilleExercice() + ", wilayaExercice=" + this.getWilayaExercice() + ", educations=" + this.getEducations() + ")";
    }
}
