// Generated by delombok at Sat Jun 27 10:20:24 GMT 2026
package com.onmm.backend.dto.medecin;

public class MedecinEducationDto {
    private Long id;
    private String diplome;
    private Long specialiteId;
    private String specialiteLibelle;
    private Long sousSpecialiteId;
    private String sousSpecialiteLibelle;
    private String universite;
    private String pays;
    private String ville;
    private Integer anneeObtention;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public MedecinEducationDto() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDiplome() {
        return this.diplome;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getSpecialiteId() {
        return this.specialiteId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSpecialiteLibelle() {
        return this.specialiteLibelle;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getSousSpecialiteId() {
        return this.sousSpecialiteId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSousSpecialiteLibelle() {
        return this.sousSpecialiteLibelle;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getUniversite() {
        return this.universite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPays() {
        return this.pays;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getVille() {
        return this.ville;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getAnneeObtention() {
        return this.anneeObtention;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDiplome(final String diplome) {
        this.diplome = diplome;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSpecialiteId(final Long specialiteId) {
        this.specialiteId = specialiteId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSpecialiteLibelle(final String specialiteLibelle) {
        this.specialiteLibelle = specialiteLibelle;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSousSpecialiteId(final Long sousSpecialiteId) {
        this.sousSpecialiteId = sousSpecialiteId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSousSpecialiteLibelle(final String sousSpecialiteLibelle) {
        this.sousSpecialiteLibelle = sousSpecialiteLibelle;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUniversite(final String universite) {
        this.universite = universite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPays(final String pays) {
        this.pays = pays;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVille(final String ville) {
        this.ville = ville;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAnneeObtention(final Integer anneeObtention) {
        this.anneeObtention = anneeObtention;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof MedecinEducationDto)) return false;
        final MedecinEducationDto other = (MedecinEducationDto) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$specialiteId = this.getSpecialiteId();
        final java.lang.Object other$specialiteId = other.getSpecialiteId();
        if (this$specialiteId == null ? other$specialiteId != null : !this$specialiteId.equals(other$specialiteId)) return false;
        final java.lang.Object this$sousSpecialiteId = this.getSousSpecialiteId();
        final java.lang.Object other$sousSpecialiteId = other.getSousSpecialiteId();
        if (this$sousSpecialiteId == null ? other$sousSpecialiteId != null : !this$sousSpecialiteId.equals(other$sousSpecialiteId)) return false;
        final java.lang.Object this$anneeObtention = this.getAnneeObtention();
        final java.lang.Object other$anneeObtention = other.getAnneeObtention();
        if (this$anneeObtention == null ? other$anneeObtention != null : !this$anneeObtention.equals(other$anneeObtention)) return false;
        final java.lang.Object this$diplome = this.getDiplome();
        final java.lang.Object other$diplome = other.getDiplome();
        if (this$diplome == null ? other$diplome != null : !this$diplome.equals(other$diplome)) return false;
        final java.lang.Object this$specialiteLibelle = this.getSpecialiteLibelle();
        final java.lang.Object other$specialiteLibelle = other.getSpecialiteLibelle();
        if (this$specialiteLibelle == null ? other$specialiteLibelle != null : !this$specialiteLibelle.equals(other$specialiteLibelle)) return false;
        final java.lang.Object this$sousSpecialiteLibelle = this.getSousSpecialiteLibelle();
        final java.lang.Object other$sousSpecialiteLibelle = other.getSousSpecialiteLibelle();
        if (this$sousSpecialiteLibelle == null ? other$sousSpecialiteLibelle != null : !this$sousSpecialiteLibelle.equals(other$sousSpecialiteLibelle)) return false;
        final java.lang.Object this$universite = this.getUniversite();
        final java.lang.Object other$universite = other.getUniversite();
        if (this$universite == null ? other$universite != null : !this$universite.equals(other$universite)) return false;
        final java.lang.Object this$pays = this.getPays();
        final java.lang.Object other$pays = other.getPays();
        if (this$pays == null ? other$pays != null : !this$pays.equals(other$pays)) return false;
        final java.lang.Object this$ville = this.getVille();
        final java.lang.Object other$ville = other.getVille();
        if (this$ville == null ? other$ville != null : !this$ville.equals(other$ville)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof MedecinEducationDto;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $specialiteId = this.getSpecialiteId();
        result = result * PRIME + ($specialiteId == null ? 43 : $specialiteId.hashCode());
        final java.lang.Object $sousSpecialiteId = this.getSousSpecialiteId();
        result = result * PRIME + ($sousSpecialiteId == null ? 43 : $sousSpecialiteId.hashCode());
        final java.lang.Object $anneeObtention = this.getAnneeObtention();
        result = result * PRIME + ($anneeObtention == null ? 43 : $anneeObtention.hashCode());
        final java.lang.Object $diplome = this.getDiplome();
        result = result * PRIME + ($diplome == null ? 43 : $diplome.hashCode());
        final java.lang.Object $specialiteLibelle = this.getSpecialiteLibelle();
        result = result * PRIME + ($specialiteLibelle == null ? 43 : $specialiteLibelle.hashCode());
        final java.lang.Object $sousSpecialiteLibelle = this.getSousSpecialiteLibelle();
        result = result * PRIME + ($sousSpecialiteLibelle == null ? 43 : $sousSpecialiteLibelle.hashCode());
        final java.lang.Object $universite = this.getUniversite();
        result = result * PRIME + ($universite == null ? 43 : $universite.hashCode());
        final java.lang.Object $pays = this.getPays();
        result = result * PRIME + ($pays == null ? 43 : $pays.hashCode());
        final java.lang.Object $ville = this.getVille();
        result = result * PRIME + ($ville == null ? 43 : $ville.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "MedecinEducationDto(id=" + this.getId() + ", diplome=" + this.getDiplome() + ", specialiteId=" + this.getSpecialiteId() + ", specialiteLibelle=" + this.getSpecialiteLibelle() + ", sousSpecialiteId=" + this.getSousSpecialiteId() + ", sousSpecialiteLibelle=" + this.getSousSpecialiteLibelle() + ", universite=" + this.getUniversite() + ", pays=" + this.getPays() + ", ville=" + this.getVille() + ", anneeObtention=" + this.getAnneeObtention() + ")";
    }
}
