// Generated by delombok at Sat Jun 27 10:20:24 GMT 2026
package com.onmm.backend.dto.medecin;

public class MedecinDocumentDto {
    private Long id;
    private String fileName;
    private String filePath;
    private String typeDocument;
    private String categorie;
    private Long size;
    private String uploadDate;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFileName() {
        return this.fileName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFilePath() {
        return this.filePath;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTypeDocument() {
        return this.typeDocument;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCategorie() {
        return this.categorie;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getSize() {
        return this.size;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getUploadDate() {
        return this.uploadDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFileName(final String fileName) {
        this.fileName = fileName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFilePath(final String filePath) {
        this.filePath = filePath;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTypeDocument(final String typeDocument) {
        this.typeDocument = typeDocument;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategorie(final String categorie) {
        this.categorie = categorie;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSize(final Long size) {
        this.size = size;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUploadDate(final String uploadDate) {
        this.uploadDate = uploadDate;
    }
}
