// Generated by delombok at Sat Jun 27 10:20:24 GMT 2026
package com.onmm.backend.dto.medecin;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

public class UpdateMedecinProfileRequest {
    @NotBlank(message = "Le nom est obligatoire")
    @Size(max = 100, message = "Le nom ne peut pas dépasser 100 caractères")
    private String nom;
    @NotBlank(message = "Le prénom est obligatoire")
    @Size(max = 100, message = "Le prénom ne peut pas dépasser 100 caractères")
    private String prenom;
    private String telephone;
    private String nationalite;
    private String adresse;
    private String wilayaExercice;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UpdateMedecinProfileRequest() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNom() {
        return this.nom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPrenom() {
        return this.prenom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTelephone() {
        return this.telephone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNationalite() {
        return this.nationalite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAdresse() {
        return this.adresse;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getWilayaExercice() {
        return this.wilayaExercice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNom(final String nom) {
        this.nom = nom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPrenom(final String prenom) {
        this.prenom = prenom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTelephone(final String telephone) {
        this.telephone = telephone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNationalite(final String nationalite) {
        this.nationalite = nationalite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAdresse(final String adresse) {
        this.adresse = adresse;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWilayaExercice(final String wilayaExercice) {
        this.wilayaExercice = wilayaExercice;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof UpdateMedecinProfileRequest)) return false;
        final UpdateMedecinProfileRequest other = (UpdateMedecinProfileRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$nom = this.getNom();
        final java.lang.Object other$nom = other.getNom();
        if (this$nom == null ? other$nom != null : !this$nom.equals(other$nom)) return false;
        final java.lang.Object this$prenom = this.getPrenom();
        final java.lang.Object other$prenom = other.getPrenom();
        if (this$prenom == null ? other$prenom != null : !this$prenom.equals(other$prenom)) return false;
        final java.lang.Object this$telephone = this.getTelephone();
        final java.lang.Object other$telephone = other.getTelephone();
        if (this$telephone == null ? other$telephone != null : !this$telephone.equals(other$telephone)) return false;
        final java.lang.Object this$nationalite = this.getNationalite();
        final java.lang.Object other$nationalite = other.getNationalite();
        if (this$nationalite == null ? other$nationalite != null : !this$nationalite.equals(other$nationalite)) return false;
        final java.lang.Object this$adresse = this.getAdresse();
        final java.lang.Object other$adresse = other.getAdresse();
        if (this$adresse == null ? other$adresse != null : !this$adresse.equals(other$adresse)) return false;
        final java.lang.Object this$wilayaExercice = this.getWilayaExercice();
        final java.lang.Object other$wilayaExercice = other.getWilayaExercice();
        if (this$wilayaExercice == null ? other$wilayaExercice != null : !this$wilayaExercice.equals(other$wilayaExercice)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof UpdateMedecinProfileRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $nom = this.getNom();
        result = result * PRIME + ($nom == null ? 43 : $nom.hashCode());
        final java.lang.Object $prenom = this.getPrenom();
        result = result * PRIME + ($prenom == null ? 43 : $prenom.hashCode());
        final java.lang.Object $telephone = this.getTelephone();
        result = result * PRIME + ($telephone == null ? 43 : $telephone.hashCode());
        final java.lang.Object $nationalite = this.getNationalite();
        result = result * PRIME + ($nationalite == null ? 43 : $nationalite.hashCode());
        final java.lang.Object $adresse = this.getAdresse();
        result = result * PRIME + ($adresse == null ? 43 : $adresse.hashCode());
        final java.lang.Object $wilayaExercice = this.getWilayaExercice();
        result = result * PRIME + ($wilayaExercice == null ? 43 : $wilayaExercice.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "UpdateMedecinProfileRequest(nom=" + this.getNom() + ", prenom=" + this.getPrenom() + ", telephone=" + this.getTelephone() + ", nationalite=" + this.getNationalite() + ", adresse=" + this.getAdresse() + ", wilayaExercice=" + this.getWilayaExercice() + ")";
    }
}
