// Generated by delombok at Sat Jun 27 10:20:23 GMT 2026
package com.onmm.backend.controller.Admin;

import com.onmm.backend.dto.Admin.DashboardStatsResponse;
import com.onmm.backend.service.Admin.AdminDashboardService;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/admin/dashboard")
@PreAuthorize("hasRole(\'ADMIN\')")
public class AdminDashboardController {
    private final AdminDashboardService dashboardService;

    @GetMapping("/stats")
    public ResponseEntity<DashboardStatsResponse> getStats() {
        return ResponseEntity.ok(dashboardService.getStats());
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AdminDashboardController(final AdminDashboardService dashboardService) {
        this.dashboardService = dashboardService;
    }
}
