// Generated by delombok at Sat Jun 27 10:20:26 GMT 2026
package com.onmm.backend.service.impl;

import com.onmm.backend.dto.contenu.*;
import com.onmm.backend.entity.*;
import com.onmm.backend.entity.enums.*;
import com.onmm.backend.mapper.ContenuMapper;
import com.onmm.backend.repository.*;
import com.onmm.backend.service.Admin.ContenuService;
import com.onmm.backend.service.FileStorageService;
import com.onmm.backend.service.NotificationService;
import org.springframework.data.domain.*;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

@Service
public class ContenuServiceImpl implements ContenuService {
    private final ContenuRepository contenuRepository;
    private final CategorieRepository categorieRepository;
    private final UserRepository userRepository;
    private final FileStorageService fileStorageService;
    private final SpecialiteRepository specialiteRepository;
    private final MedecinRepository medecinRepository;
    private final NotificationService notificationService;

    @Override
    public ContenuResponseDTO create(ContenuRequestDTO dto, MultipartFile image, Long userId) {
        CategorieContenu categorie = categorieRepository.findById(dto.getCategorieId()).orElseThrow(() -> new RuntimeException("Catégorie introuvable"));
        User user = userRepository.findById(userId).orElseThrow(() -> new RuntimeException("Utilisateur introuvable"));
        String imageUrl = fileStorageService.storeContenuImage(image);
        Specialite specialiteCible = resolveSpecialite(dto.getSpecialiteCibleId());
        Contenu contenu = Contenu.builder().titre(dto.getTitre()).resume(dto.getResume()).contenu(dto.getContenu()).type(dto.getType()).categorie(categorie).visibilite(dto.getVisibilite()).statut(ContenuStatut.DRAFT).createdBy(user).imageUrl(imageUrl).dateCreation(LocalDateTime.now()).dateExpiration(parseDate(dto.getDateExpiration())).specialiteCible(specialiteCible).build();
        return ContenuMapper.toDTO(contenuRepository.save(contenu));
    }

    @Override
    public ContenuResponseDTO update(Long id, ContenuRequestDTO dto, MultipartFile image) {
        Contenu contenu = contenuRepository.findById(id).orElseThrow(() -> new RuntimeException("Contenu introuvable"));
        CategorieContenu categorie = categorieRepository.findById(dto.getCategorieId()).orElseThrow(() -> new RuntimeException("Catégorie introuvable"));
        contenu.setTitre(dto.getTitre());
        contenu.setResume(dto.getResume());
        contenu.setContenu(dto.getContenu());
        contenu.setType(dto.getType());
        contenu.setVisibilite(dto.getVisibilite());
        contenu.setCategorie(categorie);
        contenu.setDateExpiration(parseDate(dto.getDateExpiration()));
        contenu.setSpecialiteCible(resolveSpecialite(dto.getSpecialiteCibleId()));
        if (image != null && !image.isEmpty()) {
            String imageUrl = fileStorageService.storeContenuImage(image);
            contenu.setImageUrl(imageUrl);
        }
        return ContenuMapper.toDTO(contenuRepository.save(contenu));
    }

    @Override
    public void delete(Long id) {
        contenuRepository.deleteById(id);
    }

    @Override
    public Page<ContenuResponseDTO> getAdminContenus(int page, int size) {
        Pageable pageable = PageRequest.of(page, size, Sort.by("dateCreation").descending());
        return contenuRepository.findAllByOrderByDateCreationDesc(pageable).map(ContenuMapper::toDTO);
    }

    @Override
    public ContenuResponseDTO publish(Long id) {
        Contenu contenu = contenuRepository.findById(id).orElseThrow(() -> new RuntimeException("Contenu introuvable"));
        contenu.setStatut(ContenuStatut.PUBLISHED);
        contenu.setDatePublication(LocalDateTime.now());
        Contenu saved = contenuRepository.save(contenu);
        if (saved.getVisibilite() == ContenuVisibilite.PRIVEE) {
            notifyMedecinsOfContenu(saved);
        }
        return ContenuMapper.toDTO(saved);
    }

    private void notifyMedecinsOfContenu(Contenu contenu) {
        Specialite cible = contenu.getSpecialiteCible();
        medecinRepository.findAll().stream().filter(m -> m.getStatut() == StatutMedecin.ACTIF).filter(m -> cible == null || medecinMatchesSpecialite(m, cible)).forEach(m -> notificationService.createMedecinNotification(m.getEmail(), "NOUVEAU_CONTENU", "Nouveau contenu publié", "L\'ONMM a publié : " + contenu.getTitre(), "/medecin/contenus/" + contenu.getId(), false));
    }

    private boolean medecinMatchesSpecialite(Medecin medecin, Specialite cible) {
        if (medecin.getEducations() == null || medecin.getEducations().isEmpty()) {
            return false;
        }
        MedecinEducation reference = medecin.getEducations().stream().max(Comparator.comparing(MedecinEducation::getAnneeObtention)).orElse(null);
        return reference != null && reference.getSpecialite() != null && reference.getSpecialite().getId().equals(cible.getId());
    }

    @Override
    public ContenuResponseDTO unpublish(Long id) {
        Contenu contenu = contenuRepository.findById(id).orElseThrow(() -> new RuntimeException("Contenu introuvable"));
        contenu.setStatut(ContenuStatut.DRAFT);
        contenu.setDatePublication(null);
        return ContenuMapper.toDTO(contenuRepository.save(contenu));
    }

    @Override
    public Page<ContenuResponseDTO> getPublicContenus(Long categorieId, int page, int size) {
        Pageable pageable = PageRequest.of(page, size, Sort.by("datePublication").descending());
        Page<Contenu> contenus = categorieId != null ? contenuRepository.findByStatutAndVisibiliteAndCategorie_Id(ContenuStatut.PUBLISHED, ContenuVisibilite.PUBLIC, categorieId, pageable) : contenuRepository.findByStatutAndVisibilite(ContenuStatut.PUBLISHED, ContenuVisibilite.PUBLIC, pageable);
        return contenus.map(ContenuMapper::toDTO);
    }

    @Override
    @Scheduled(fixedRate = 3600000)
    public void expireContenus() {
        contenuRepository.findAll().forEach(contenu -> {
            if (contenu.getDateExpiration() != null && contenu.getDateExpiration().isBefore(LocalDateTime.now()) && contenu.getStatut() == ContenuStatut.PUBLISHED) {
                contenu.setStatut(ContenuStatut.EXPIRED);
                contenuRepository.save(contenu);
            }
        });
    }

    @Override
    @org.springframework.transaction.annotation.Transactional(readOnly = true)
    public Page<ContenuResponseDTO> getMedecinContenus(Long medecinId, int page, int size) {
        Medecin medecin = medecinRepository.findById(medecinId).orElseThrow(() -> new RuntimeException("Médecin introuvable"));
        List<Long> specialiteIds = medecin.getEducations().stream().filter(e -> e.getSpecialite() != null).map(e -> e.getSpecialite().getId()).distinct().collect(java.util.stream.Collectors.toList());
        if (specialiteIds.isEmpty()) {
            specialiteIds = new ArrayList<>(List.of(-1L));
        }
        Pageable pageable = PageRequest.of(page, size, Sort.by("datePublication").descending());
        return contenuRepository.findMedecinContenus(specialiteIds, pageable).map(ContenuMapper::toDTO);
    }

    private Specialite resolveSpecialite(Long specialiteCibleId) {
        if (specialiteCibleId == null) return null;
        return specialiteRepository.findById(specialiteCibleId).orElseThrow(() -> new RuntimeException("Spécialité introuvable"));
    }

    private LocalDateTime parseDate(String value) {
        if (value == null || value.isBlank()) {
            return null;
        }
        return LocalDateTime.parse(value);
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ContenuServiceImpl(final ContenuRepository contenuRepository, final CategorieRepository categorieRepository, final UserRepository userRepository, final FileStorageService fileStorageService, final SpecialiteRepository specialiteRepository, final MedecinRepository medecinRepository, final NotificationService notificationService) {
        this.contenuRepository = contenuRepository;
        this.categorieRepository = categorieRepository;
        this.userRepository = userRepository;
        this.fileStorageService = fileStorageService;
        this.specialiteRepository = specialiteRepository;
        this.medecinRepository = medecinRepository;
        this.notificationService = notificationService;
    }
}
