// Generated by delombok at Sat Jun 27 10:20:24 GMT 2026
package com.onmm.backend.dto.publics;

import com.onmm.backend.entity.Specialite;
import java.util.List;

public class PublicMedecinDetailResponse {
    private Long id;
    private String nom;
    private String prenom;
    private String numeroInscription;
    private String ville;
    private String photoProfilPath;
    private String statut;
    private String sexe;
    private String adresse;
    private String nationalite;
    private List<PublicEducationDto> educations;
    private List<PublicExperienceDto> experiences;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PublicMedecinDetailResponse() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNom() {
        return this.nom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPrenom() {
        return this.prenom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNumeroInscription() {
        return this.numeroInscription;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getVille() {
        return this.ville;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPhotoProfilPath() {
        return this.photoProfilPath;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatut() {
        return this.statut;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSexe() {
        return this.sexe;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAdresse() {
        return this.adresse;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNationalite() {
        return this.nationalite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<PublicEducationDto> getEducations() {
        return this.educations;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<PublicExperienceDto> getExperiences() {
        return this.experiences;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNom(final String nom) {
        this.nom = nom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPrenom(final String prenom) {
        this.prenom = prenom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNumeroInscription(final String numeroInscription) {
        this.numeroInscription = numeroInscription;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVille(final String ville) {
        this.ville = ville;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPhotoProfilPath(final String photoProfilPath) {
        this.photoProfilPath = photoProfilPath;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatut(final String statut) {
        this.statut = statut;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSexe(final String sexe) {
        this.sexe = sexe;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAdresse(final String adresse) {
        this.adresse = adresse;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNationalite(final String nationalite) {
        this.nationalite = nationalite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEducations(final List<PublicEducationDto> educations) {
        this.educations = educations;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setExperiences(final List<PublicExperienceDto> experiences) {
        this.experiences = experiences;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PublicMedecinDetailResponse)) return false;
        final PublicMedecinDetailResponse other = (PublicMedecinDetailResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$nom = this.getNom();
        final java.lang.Object other$nom = other.getNom();
        if (this$nom == null ? other$nom != null : !this$nom.equals(other$nom)) return false;
        final java.lang.Object this$prenom = this.getPrenom();
        final java.lang.Object other$prenom = other.getPrenom();
        if (this$prenom == null ? other$prenom != null : !this$prenom.equals(other$prenom)) return false;
        final java.lang.Object this$numeroInscription = this.getNumeroInscription();
        final java.lang.Object other$numeroInscription = other.getNumeroInscription();
        if (this$numeroInscription == null ? other$numeroInscription != null : !this$numeroInscription.equals(other$numeroInscription)) return false;
        final java.lang.Object this$ville = this.getVille();
        final java.lang.Object other$ville = other.getVille();
        if (this$ville == null ? other$ville != null : !this$ville.equals(other$ville)) return false;
        final java.lang.Object this$photoProfilPath = this.getPhotoProfilPath();
        final java.lang.Object other$photoProfilPath = other.getPhotoProfilPath();
        if (this$photoProfilPath == null ? other$photoProfilPath != null : !this$photoProfilPath.equals(other$photoProfilPath)) return false;
        final java.lang.Object this$statut = this.getStatut();
        final java.lang.Object other$statut = other.getStatut();
        if (this$statut == null ? other$statut != null : !this$statut.equals(other$statut)) return false;
        final java.lang.Object this$sexe = this.getSexe();
        final java.lang.Object other$sexe = other.getSexe();
        if (this$sexe == null ? other$sexe != null : !this$sexe.equals(other$sexe)) return false;
        final java.lang.Object this$adresse = this.getAdresse();
        final java.lang.Object other$adresse = other.getAdresse();
        if (this$adresse == null ? other$adresse != null : !this$adresse.equals(other$adresse)) return false;
        final java.lang.Object this$nationalite = this.getNationalite();
        final java.lang.Object other$nationalite = other.getNationalite();
        if (this$nationalite == null ? other$nationalite != null : !this$nationalite.equals(other$nationalite)) return false;
        final java.lang.Object this$educations = this.getEducations();
        final java.lang.Object other$educations = other.getEducations();
        if (this$educations == null ? other$educations != null : !this$educations.equals(other$educations)) return false;
        final java.lang.Object this$experiences = this.getExperiences();
        final java.lang.Object other$experiences = other.getExperiences();
        if (this$experiences == null ? other$experiences != null : !this$experiences.equals(other$experiences)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PublicMedecinDetailResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $nom = this.getNom();
        result = result * PRIME + ($nom == null ? 43 : $nom.hashCode());
        final java.lang.Object $prenom = this.getPrenom();
        result = result * PRIME + ($prenom == null ? 43 : $prenom.hashCode());
        final java.lang.Object $numeroInscription = this.getNumeroInscription();
        result = result * PRIME + ($numeroInscription == null ? 43 : $numeroInscription.hashCode());
        final java.lang.Object $ville = this.getVille();
        result = result * PRIME + ($ville == null ? 43 : $ville.hashCode());
        final java.lang.Object $photoProfilPath = this.getPhotoProfilPath();
        result = result * PRIME + ($photoProfilPath == null ? 43 : $photoProfilPath.hashCode());
        final java.lang.Object $statut = this.getStatut();
        result = result * PRIME + ($statut == null ? 43 : $statut.hashCode());
        final java.lang.Object $sexe = this.getSexe();
        result = result * PRIME + ($sexe == null ? 43 : $sexe.hashCode());
        final java.lang.Object $adresse = this.getAdresse();
        result = result * PRIME + ($adresse == null ? 43 : $adresse.hashCode());
        final java.lang.Object $nationalite = this.getNationalite();
        result = result * PRIME + ($nationalite == null ? 43 : $nationalite.hashCode());
        final java.lang.Object $educations = this.getEducations();
        result = result * PRIME + ($educations == null ? 43 : $educations.hashCode());
        final java.lang.Object $experiences = this.getExperiences();
        result = result * PRIME + ($experiences == null ? 43 : $experiences.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "PublicMedecinDetailResponse(id=" + this.getId() + ", nom=" + this.getNom() + ", prenom=" + this.getPrenom() + ", numeroInscription=" + this.getNumeroInscription() + ", ville=" + this.getVille() + ", photoProfilPath=" + this.getPhotoProfilPath() + ", statut=" + this.getStatut() + ", sexe=" + this.getSexe() + ", adresse=" + this.getAdresse() + ", nationalite=" + this.getNationalite() + ", educations=" + this.getEducations() + ", experiences=" + this.getExperiences() + ")";
    }
}
