// Generated by delombok at Sat Jun 27 10:20:24 GMT 2026
package com.onmm.backend.dto.publics;

import java.time.LocalDate;

public class PublicExperienceDto {
    private String poste;
    private String nomEtablissement;
    private String ville;
    private String pays;
    private String dateDebut;
    private String dateFin;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PublicExperienceDto() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPoste() {
        return this.poste;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNomEtablissement() {
        return this.nomEtablissement;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getVille() {
        return this.ville;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPays() {
        return this.pays;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDateDebut() {
        return this.dateDebut;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDateFin() {
        return this.dateFin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPoste(final String poste) {
        this.poste = poste;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNomEtablissement(final String nomEtablissement) {
        this.nomEtablissement = nomEtablissement;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVille(final String ville) {
        this.ville = ville;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPays(final String pays) {
        this.pays = pays;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDateDebut(final String dateDebut) {
        this.dateDebut = dateDebut;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDateFin(final String dateFin) {
        this.dateFin = dateFin;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PublicExperienceDto)) return false;
        final PublicExperienceDto other = (PublicExperienceDto) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$poste = this.getPoste();
        final java.lang.Object other$poste = other.getPoste();
        if (this$poste == null ? other$poste != null : !this$poste.equals(other$poste)) return false;
        final java.lang.Object this$nomEtablissement = this.getNomEtablissement();
        final java.lang.Object other$nomEtablissement = other.getNomEtablissement();
        if (this$nomEtablissement == null ? other$nomEtablissement != null : !this$nomEtablissement.equals(other$nomEtablissement)) return false;
        final java.lang.Object this$ville = this.getVille();
        final java.lang.Object other$ville = other.getVille();
        if (this$ville == null ? other$ville != null : !this$ville.equals(other$ville)) return false;
        final java.lang.Object this$pays = this.getPays();
        final java.lang.Object other$pays = other.getPays();
        if (this$pays == null ? other$pays != null : !this$pays.equals(other$pays)) return false;
        final java.lang.Object this$dateDebut = this.getDateDebut();
        final java.lang.Object other$dateDebut = other.getDateDebut();
        if (this$dateDebut == null ? other$dateDebut != null : !this$dateDebut.equals(other$dateDebut)) return false;
        final java.lang.Object this$dateFin = this.getDateFin();
        final java.lang.Object other$dateFin = other.getDateFin();
        if (this$dateFin == null ? other$dateFin != null : !this$dateFin.equals(other$dateFin)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PublicExperienceDto;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $poste = this.getPoste();
        result = result * PRIME + ($poste == null ? 43 : $poste.hashCode());
        final java.lang.Object $nomEtablissement = this.getNomEtablissement();
        result = result * PRIME + ($nomEtablissement == null ? 43 : $nomEtablissement.hashCode());
        final java.lang.Object $ville = this.getVille();
        result = result * PRIME + ($ville == null ? 43 : $ville.hashCode());
        final java.lang.Object $pays = this.getPays();
        result = result * PRIME + ($pays == null ? 43 : $pays.hashCode());
        final java.lang.Object $dateDebut = this.getDateDebut();
        result = result * PRIME + ($dateDebut == null ? 43 : $dateDebut.hashCode());
        final java.lang.Object $dateFin = this.getDateFin();
        result = result * PRIME + ($dateFin == null ? 43 : $dateFin.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "PublicExperienceDto(poste=" + this.getPoste() + ", nomEtablissement=" + this.getNomEtablissement() + ", ville=" + this.getVille() + ", pays=" + this.getPays() + ", dateDebut=" + this.getDateDebut() + ", dateFin=" + this.getDateFin() + ")";
    }
}
