// Generated by delombok at Sat Jun 27 10:20:24 GMT 2026
package com.onmm.backend.dto.publics;

import com.onmm.backend.entity.Specialite;
import java.util.List;

public class PublicMedecinResponse {
    private Long id;
    private String nom;
    private String prenom;
    private String numeroInscription;
    private String wilayaExercice;
    private String structureExercice;
    private String photoProfilPath;
    private List<PublicEducationDto> educations;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PublicMedecinResponse() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNom() {
        return this.nom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPrenom() {
        return this.prenom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNumeroInscription() {
        return this.numeroInscription;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getWilayaExercice() {
        return this.wilayaExercice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStructureExercice() {
        return this.structureExercice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPhotoProfilPath() {
        return this.photoProfilPath;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<PublicEducationDto> getEducations() {
        return this.educations;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNom(final String nom) {
        this.nom = nom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPrenom(final String prenom) {
        this.prenom = prenom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNumeroInscription(final String numeroInscription) {
        this.numeroInscription = numeroInscription;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWilayaExercice(final String wilayaExercice) {
        this.wilayaExercice = wilayaExercice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStructureExercice(final String structureExercice) {
        this.structureExercice = structureExercice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPhotoProfilPath(final String photoProfilPath) {
        this.photoProfilPath = photoProfilPath;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEducations(final List<PublicEducationDto> educations) {
        this.educations = educations;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PublicMedecinResponse)) return false;
        final PublicMedecinResponse other = (PublicMedecinResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$nom = this.getNom();
        final java.lang.Object other$nom = other.getNom();
        if (this$nom == null ? other$nom != null : !this$nom.equals(other$nom)) return false;
        final java.lang.Object this$prenom = this.getPrenom();
        final java.lang.Object other$prenom = other.getPrenom();
        if (this$prenom == null ? other$prenom != null : !this$prenom.equals(other$prenom)) return false;
        final java.lang.Object this$numeroInscription = this.getNumeroInscription();
        final java.lang.Object other$numeroInscription = other.getNumeroInscription();
        if (this$numeroInscription == null ? other$numeroInscription != null : !this$numeroInscription.equals(other$numeroInscription)) return false;
        final java.lang.Object this$wilayaExercice = this.getWilayaExercice();
        final java.lang.Object other$wilayaExercice = other.getWilayaExercice();
        if (this$wilayaExercice == null ? other$wilayaExercice != null : !this$wilayaExercice.equals(other$wilayaExercice)) return false;
        final java.lang.Object this$structureExercice = this.getStructureExercice();
        final java.lang.Object other$structureExercice = other.getStructureExercice();
        if (this$structureExercice == null ? other$structureExercice != null : !this$structureExercice.equals(other$structureExercice)) return false;
        final java.lang.Object this$photoProfilPath = this.getPhotoProfilPath();
        final java.lang.Object other$photoProfilPath = other.getPhotoProfilPath();
        if (this$photoProfilPath == null ? other$photoProfilPath != null : !this$photoProfilPath.equals(other$photoProfilPath)) return false;
        final java.lang.Object this$educations = this.getEducations();
        final java.lang.Object other$educations = other.getEducations();
        if (this$educations == null ? other$educations != null : !this$educations.equals(other$educations)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PublicMedecinResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $nom = this.getNom();
        result = result * PRIME + ($nom == null ? 43 : $nom.hashCode());
        final java.lang.Object $prenom = this.getPrenom();
        result = result * PRIME + ($prenom == null ? 43 : $prenom.hashCode());
        final java.lang.Object $numeroInscription = this.getNumeroInscription();
        result = result * PRIME + ($numeroInscription == null ? 43 : $numeroInscription.hashCode());
        final java.lang.Object $wilayaExercice = this.getWilayaExercice();
        result = result * PRIME + ($wilayaExercice == null ? 43 : $wilayaExercice.hashCode());
        final java.lang.Object $structureExercice = this.getStructureExercice();
        result = result * PRIME + ($structureExercice == null ? 43 : $structureExercice.hashCode());
        final java.lang.Object $photoProfilPath = this.getPhotoProfilPath();
        result = result * PRIME + ($photoProfilPath == null ? 43 : $photoProfilPath.hashCode());
        final java.lang.Object $educations = this.getEducations();
        result = result * PRIME + ($educations == null ? 43 : $educations.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "PublicMedecinResponse(id=" + this.getId() + ", nom=" + this.getNom() + ", prenom=" + this.getPrenom() + ", numeroInscription=" + this.getNumeroInscription() + ", wilayaExercice=" + this.getWilayaExercice() + ", structureExercice=" + this.getStructureExercice() + ", photoProfilPath=" + this.getPhotoProfilPath() + ", educations=" + this.getEducations() + ")";
    }
}
