// Generated by delombok at Sat Jun 27 10:20:24 GMT 2026
package com.onmm.backend.dto.publics;

public class PublicMedecinSearchRequest {
    private String nom;
    private String prenom;
    private String numeroInscription;
    private String specialite;
    private String wilaya;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PublicMedecinSearchRequest() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNom() {
        return this.nom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPrenom() {
        return this.prenom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNumeroInscription() {
        return this.numeroInscription;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSpecialite() {
        return this.specialite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getWilaya() {
        return this.wilaya;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNom(final String nom) {
        this.nom = nom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPrenom(final String prenom) {
        this.prenom = prenom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNumeroInscription(final String numeroInscription) {
        this.numeroInscription = numeroInscription;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSpecialite(final String specialite) {
        this.specialite = specialite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWilaya(final String wilaya) {
        this.wilaya = wilaya;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PublicMedecinSearchRequest)) return false;
        final PublicMedecinSearchRequest other = (PublicMedecinSearchRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$nom = this.getNom();
        final java.lang.Object other$nom = other.getNom();
        if (this$nom == null ? other$nom != null : !this$nom.equals(other$nom)) return false;
        final java.lang.Object this$prenom = this.getPrenom();
        final java.lang.Object other$prenom = other.getPrenom();
        if (this$prenom == null ? other$prenom != null : !this$prenom.equals(other$prenom)) return false;
        final java.lang.Object this$numeroInscription = this.getNumeroInscription();
        final java.lang.Object other$numeroInscription = other.getNumeroInscription();
        if (this$numeroInscription == null ? other$numeroInscription != null : !this$numeroInscription.equals(other$numeroInscription)) return false;
        final java.lang.Object this$specialite = this.getSpecialite();
        final java.lang.Object other$specialite = other.getSpecialite();
        if (this$specialite == null ? other$specialite != null : !this$specialite.equals(other$specialite)) return false;
        final java.lang.Object this$wilaya = this.getWilaya();
        final java.lang.Object other$wilaya = other.getWilaya();
        if (this$wilaya == null ? other$wilaya != null : !this$wilaya.equals(other$wilaya)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PublicMedecinSearchRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $nom = this.getNom();
        result = result * PRIME + ($nom == null ? 43 : $nom.hashCode());
        final java.lang.Object $prenom = this.getPrenom();
        result = result * PRIME + ($prenom == null ? 43 : $prenom.hashCode());
        final java.lang.Object $numeroInscription = this.getNumeroInscription();
        result = result * PRIME + ($numeroInscription == null ? 43 : $numeroInscription.hashCode());
        final java.lang.Object $specialite = this.getSpecialite();
        result = result * PRIME + ($specialite == null ? 43 : $specialite.hashCode());
        final java.lang.Object $wilaya = this.getWilaya();
        result = result * PRIME + ($wilaya == null ? 43 : $wilaya.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "PublicMedecinSearchRequest(nom=" + this.getNom() + ", prenom=" + this.getPrenom() + ", numeroInscription=" + this.getNumeroInscription() + ", specialite=" + this.getSpecialite() + ", wilaya=" + this.getWilaya() + ")";
    }
}
