package com.onmm.backend.entity.enums;

public enum ReclamationCategory {
    RETARD_TRAITEMENT,
    ERREUR_DOSSIER,
    DEMANDE_INFORMATION,
    QUALITE_SOINS,
    INFORMATION_CONSENTEMENT,
    SECRET_PROFESSIONNEL,
    COMPORTEMENT_INAPPROPRIE,
    CERTIFICAT_MEDICAL,
    PRESCRIPTION_ABUSIVE,
    CONFRATERNITE,
    PUBLICITE_CHARLATANISME,
    DECONSIDERATION_PROFESSION,
    AUTRE
}