// Generated by delombok at Sat Jun 27 10:20:23 GMT 2026
package com.onmm.backend.dto.Admin;

import com.onmm.backend.entity.Specialite;
import com.onmm.backend.entity.enums.StatutMedecin;
import java.time.LocalDate;

public class AdminMedecinListResponse {
    private Long id;
    private String numeroInscription;
    private String nom;
    private String prenom;
    private String email;
    private String telephone;
    private Long specialiteId;
    private String specialiteLibelle;
    private Long sousSpecialiteId;
    private String sousSpecialiteLibelle;
    private StatutMedecin statut;
    private LocalDate dateNaissance;
    private String sexe;
    private String nni;
    private String wilayaExercice;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AdminMedecinListResponse() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNumeroInscription() {
        return this.numeroInscription;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNom() {
        return this.nom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPrenom() {
        return this.prenom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTelephone() {
        return this.telephone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getSpecialiteId() {
        return this.specialiteId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSpecialiteLibelle() {
        return this.specialiteLibelle;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getSousSpecialiteId() {
        return this.sousSpecialiteId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSousSpecialiteLibelle() {
        return this.sousSpecialiteLibelle;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public StatutMedecin getStatut() {
        return this.statut;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDate getDateNaissance() {
        return this.dateNaissance;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSexe() {
        return this.sexe;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNni() {
        return this.nni;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getWilayaExercice() {
        return this.wilayaExercice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNumeroInscription(final String numeroInscription) {
        this.numeroInscription = numeroInscription;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNom(final String nom) {
        this.nom = nom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPrenom(final String prenom) {
        this.prenom = prenom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTelephone(final String telephone) {
        this.telephone = telephone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSpecialiteId(final Long specialiteId) {
        this.specialiteId = specialiteId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSpecialiteLibelle(final String specialiteLibelle) {
        this.specialiteLibelle = specialiteLibelle;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSousSpecialiteId(final Long sousSpecialiteId) {
        this.sousSpecialiteId = sousSpecialiteId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSousSpecialiteLibelle(final String sousSpecialiteLibelle) {
        this.sousSpecialiteLibelle = sousSpecialiteLibelle;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatut(final StatutMedecin statut) {
        this.statut = statut;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDateNaissance(final LocalDate dateNaissance) {
        this.dateNaissance = dateNaissance;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSexe(final String sexe) {
        this.sexe = sexe;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNni(final String nni) {
        this.nni = nni;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWilayaExercice(final String wilayaExercice) {
        this.wilayaExercice = wilayaExercice;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AdminMedecinListResponse)) return false;
        final AdminMedecinListResponse other = (AdminMedecinListResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$specialiteId = this.getSpecialiteId();
        final java.lang.Object other$specialiteId = other.getSpecialiteId();
        if (this$specialiteId == null ? other$specialiteId != null : !this$specialiteId.equals(other$specialiteId)) return false;
        final java.lang.Object this$sousSpecialiteId = this.getSousSpecialiteId();
        final java.lang.Object other$sousSpecialiteId = other.getSousSpecialiteId();
        if (this$sousSpecialiteId == null ? other$sousSpecialiteId != null : !this$sousSpecialiteId.equals(other$sousSpecialiteId)) return false;
        final java.lang.Object this$numeroInscription = this.getNumeroInscription();
        final java.lang.Object other$numeroInscription = other.getNumeroInscription();
        if (this$numeroInscription == null ? other$numeroInscription != null : !this$numeroInscription.equals(other$numeroInscription)) return false;
        final java.lang.Object this$nom = this.getNom();
        final java.lang.Object other$nom = other.getNom();
        if (this$nom == null ? other$nom != null : !this$nom.equals(other$nom)) return false;
        final java.lang.Object this$prenom = this.getPrenom();
        final java.lang.Object other$prenom = other.getPrenom();
        if (this$prenom == null ? other$prenom != null : !this$prenom.equals(other$prenom)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$telephone = this.getTelephone();
        final java.lang.Object other$telephone = other.getTelephone();
        if (this$telephone == null ? other$telephone != null : !this$telephone.equals(other$telephone)) return false;
        final java.lang.Object this$specialiteLibelle = this.getSpecialiteLibelle();
        final java.lang.Object other$specialiteLibelle = other.getSpecialiteLibelle();
        if (this$specialiteLibelle == null ? other$specialiteLibelle != null : !this$specialiteLibelle.equals(other$specialiteLibelle)) return false;
        final java.lang.Object this$sousSpecialiteLibelle = this.getSousSpecialiteLibelle();
        final java.lang.Object other$sousSpecialiteLibelle = other.getSousSpecialiteLibelle();
        if (this$sousSpecialiteLibelle == null ? other$sousSpecialiteLibelle != null : !this$sousSpecialiteLibelle.equals(other$sousSpecialiteLibelle)) return false;
        final java.lang.Object this$statut = this.getStatut();
        final java.lang.Object other$statut = other.getStatut();
        if (this$statut == null ? other$statut != null : !this$statut.equals(other$statut)) return false;
        final java.lang.Object this$dateNaissance = this.getDateNaissance();
        final java.lang.Object other$dateNaissance = other.getDateNaissance();
        if (this$dateNaissance == null ? other$dateNaissance != null : !this$dateNaissance.equals(other$dateNaissance)) return false;
        final java.lang.Object this$sexe = this.getSexe();
        final java.lang.Object other$sexe = other.getSexe();
        if (this$sexe == null ? other$sexe != null : !this$sexe.equals(other$sexe)) return false;
        final java.lang.Object this$nni = this.getNni();
        final java.lang.Object other$nni = other.getNni();
        if (this$nni == null ? other$nni != null : !this$nni.equals(other$nni)) return false;
        final java.lang.Object this$wilayaExercice = this.getWilayaExercice();
        final java.lang.Object other$wilayaExercice = other.getWilayaExercice();
        if (this$wilayaExercice == null ? other$wilayaExercice != null : !this$wilayaExercice.equals(other$wilayaExercice)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AdminMedecinListResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $specialiteId = this.getSpecialiteId();
        result = result * PRIME + ($specialiteId == null ? 43 : $specialiteId.hashCode());
        final java.lang.Object $sousSpecialiteId = this.getSousSpecialiteId();
        result = result * PRIME + ($sousSpecialiteId == null ? 43 : $sousSpecialiteId.hashCode());
        final java.lang.Object $numeroInscription = this.getNumeroInscription();
        result = result * PRIME + ($numeroInscription == null ? 43 : $numeroInscription.hashCode());
        final java.lang.Object $nom = this.getNom();
        result = result * PRIME + ($nom == null ? 43 : $nom.hashCode());
        final java.lang.Object $prenom = this.getPrenom();
        result = result * PRIME + ($prenom == null ? 43 : $prenom.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $telephone = this.getTelephone();
        result = result * PRIME + ($telephone == null ? 43 : $telephone.hashCode());
        final java.lang.Object $specialiteLibelle = this.getSpecialiteLibelle();
        result = result * PRIME + ($specialiteLibelle == null ? 43 : $specialiteLibelle.hashCode());
        final java.lang.Object $sousSpecialiteLibelle = this.getSousSpecialiteLibelle();
        result = result * PRIME + ($sousSpecialiteLibelle == null ? 43 : $sousSpecialiteLibelle.hashCode());
        final java.lang.Object $statut = this.getStatut();
        result = result * PRIME + ($statut == null ? 43 : $statut.hashCode());
        final java.lang.Object $dateNaissance = this.getDateNaissance();
        result = result * PRIME + ($dateNaissance == null ? 43 : $dateNaissance.hashCode());
        final java.lang.Object $sexe = this.getSexe();
        result = result * PRIME + ($sexe == null ? 43 : $sexe.hashCode());
        final java.lang.Object $nni = this.getNni();
        result = result * PRIME + ($nni == null ? 43 : $nni.hashCode());
        final java.lang.Object $wilayaExercice = this.getWilayaExercice();
        result = result * PRIME + ($wilayaExercice == null ? 43 : $wilayaExercice.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "AdminMedecinListResponse(id=" + this.getId() + ", numeroInscription=" + this.getNumeroInscription() + ", nom=" + this.getNom() + ", prenom=" + this.getPrenom() + ", email=" + this.getEmail() + ", telephone=" + this.getTelephone() + ", specialiteId=" + this.getSpecialiteId() + ", specialiteLibelle=" + this.getSpecialiteLibelle() + ", sousSpecialiteId=" + this.getSousSpecialiteId() + ", sousSpecialiteLibelle=" + this.getSousSpecialiteLibelle() + ", statut=" + this.getStatut() + ", dateNaissance=" + this.getDateNaissance() + ", sexe=" + this.getSexe() + ", nni=" + this.getNni() + ", wilayaExercice=" + this.getWilayaExercice() + ")";
    }
}
