// Generated by delombok at Sat Jun 27 10:20:23 GMT 2026
package com.onmm.backend.dto.Admin;

public class AdminProfileResponse {
    private Long id;
    private String nomComplet;
    private String email;
    private String telephone;
    private String photoProfilPath;
    private String dateCreation;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AdminProfileResponse() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNomComplet() {
        return this.nomComplet;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTelephone() {
        return this.telephone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPhotoProfilPath() {
        return this.photoProfilPath;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDateCreation() {
        return this.dateCreation;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNomComplet(final String nomComplet) {
        this.nomComplet = nomComplet;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTelephone(final String telephone) {
        this.telephone = telephone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPhotoProfilPath(final String photoProfilPath) {
        this.photoProfilPath = photoProfilPath;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDateCreation(final String dateCreation) {
        this.dateCreation = dateCreation;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AdminProfileResponse)) return false;
        final AdminProfileResponse other = (AdminProfileResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$nomComplet = this.getNomComplet();
        final java.lang.Object other$nomComplet = other.getNomComplet();
        if (this$nomComplet == null ? other$nomComplet != null : !this$nomComplet.equals(other$nomComplet)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$telephone = this.getTelephone();
        final java.lang.Object other$telephone = other.getTelephone();
        if (this$telephone == null ? other$telephone != null : !this$telephone.equals(other$telephone)) return false;
        final java.lang.Object this$photoProfilPath = this.getPhotoProfilPath();
        final java.lang.Object other$photoProfilPath = other.getPhotoProfilPath();
        if (this$photoProfilPath == null ? other$photoProfilPath != null : !this$photoProfilPath.equals(other$photoProfilPath)) return false;
        final java.lang.Object this$dateCreation = this.getDateCreation();
        final java.lang.Object other$dateCreation = other.getDateCreation();
        if (this$dateCreation == null ? other$dateCreation != null : !this$dateCreation.equals(other$dateCreation)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AdminProfileResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $nomComplet = this.getNomComplet();
        result = result * PRIME + ($nomComplet == null ? 43 : $nomComplet.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $telephone = this.getTelephone();
        result = result * PRIME + ($telephone == null ? 43 : $telephone.hashCode());
        final java.lang.Object $photoProfilPath = this.getPhotoProfilPath();
        result = result * PRIME + ($photoProfilPath == null ? 43 : $photoProfilPath.hashCode());
        final java.lang.Object $dateCreation = this.getDateCreation();
        result = result * PRIME + ($dateCreation == null ? 43 : $dateCreation.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "AdminProfileResponse(id=" + this.getId() + ", nomComplet=" + this.getNomComplet() + ", email=" + this.getEmail() + ", telephone=" + this.getTelephone() + ", photoProfilPath=" + this.getPhotoProfilPath() + ", dateCreation=" + this.getDateCreation() + ")";
    }
}
