// Generated by delombok at Sat Jun 27 10:20:23 GMT 2026
package com.onmm.backend.dto.Admin;

import com.onmm.backend.dto.DemandeDocumentResponse;
import com.onmm.backend.dto.DemandeEducationResponse;
import com.onmm.backend.dto.DemandeExperienceResponse;
import java.time.LocalDateTime;
import java.util.List;

public class AdminDemandeResponse {
    private Long id;
    private String nom;
    private String prenom;
    private String email;
    private String statut;
    private LocalDateTime submissionDate;
    private List<DemandeEducationResponse> educations;
    private List<DemandeExperienceResponse> experiences;
    private List<DemandeDocumentResponse> documents;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AdminDemandeResponse() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNom() {
        return this.nom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPrenom() {
        return this.prenom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatut() {
        return this.statut;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getSubmissionDate() {
        return this.submissionDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<DemandeEducationResponse> getEducations() {
        return this.educations;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<DemandeExperienceResponse> getExperiences() {
        return this.experiences;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<DemandeDocumentResponse> getDocuments() {
        return this.documents;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNom(final String nom) {
        this.nom = nom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPrenom(final String prenom) {
        this.prenom = prenom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatut(final String statut) {
        this.statut = statut;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSubmissionDate(final LocalDateTime submissionDate) {
        this.submissionDate = submissionDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEducations(final List<DemandeEducationResponse> educations) {
        this.educations = educations;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setExperiences(final List<DemandeExperienceResponse> experiences) {
        this.experiences = experiences;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDocuments(final List<DemandeDocumentResponse> documents) {
        this.documents = documents;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AdminDemandeResponse)) return false;
        final AdminDemandeResponse other = (AdminDemandeResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$nom = this.getNom();
        final java.lang.Object other$nom = other.getNom();
        if (this$nom == null ? other$nom != null : !this$nom.equals(other$nom)) return false;
        final java.lang.Object this$prenom = this.getPrenom();
        final java.lang.Object other$prenom = other.getPrenom();
        if (this$prenom == null ? other$prenom != null : !this$prenom.equals(other$prenom)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$statut = this.getStatut();
        final java.lang.Object other$statut = other.getStatut();
        if (this$statut == null ? other$statut != null : !this$statut.equals(other$statut)) return false;
        final java.lang.Object this$submissionDate = this.getSubmissionDate();
        final java.lang.Object other$submissionDate = other.getSubmissionDate();
        if (this$submissionDate == null ? other$submissionDate != null : !this$submissionDate.equals(other$submissionDate)) return false;
        final java.lang.Object this$educations = this.getEducations();
        final java.lang.Object other$educations = other.getEducations();
        if (this$educations == null ? other$educations != null : !this$educations.equals(other$educations)) return false;
        final java.lang.Object this$experiences = this.getExperiences();
        final java.lang.Object other$experiences = other.getExperiences();
        if (this$experiences == null ? other$experiences != null : !this$experiences.equals(other$experiences)) return false;
        final java.lang.Object this$documents = this.getDocuments();
        final java.lang.Object other$documents = other.getDocuments();
        if (this$documents == null ? other$documents != null : !this$documents.equals(other$documents)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AdminDemandeResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $nom = this.getNom();
        result = result * PRIME + ($nom == null ? 43 : $nom.hashCode());
        final java.lang.Object $prenom = this.getPrenom();
        result = result * PRIME + ($prenom == null ? 43 : $prenom.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $statut = this.getStatut();
        result = result * PRIME + ($statut == null ? 43 : $statut.hashCode());
        final java.lang.Object $submissionDate = this.getSubmissionDate();
        result = result * PRIME + ($submissionDate == null ? 43 : $submissionDate.hashCode());
        final java.lang.Object $educations = this.getEducations();
        result = result * PRIME + ($educations == null ? 43 : $educations.hashCode());
        final java.lang.Object $experiences = this.getExperiences();
        result = result * PRIME + ($experiences == null ? 43 : $experiences.hashCode());
        final java.lang.Object $documents = this.getDocuments();
        result = result * PRIME + ($documents == null ? 43 : $documents.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "AdminDemandeResponse(id=" + this.getId() + ", nom=" + this.getNom() + ", prenom=" + this.getPrenom() + ", email=" + this.getEmail() + ", statut=" + this.getStatut() + ", submissionDate=" + this.getSubmissionDate() + ", educations=" + this.getEducations() + ", experiences=" + this.getExperiences() + ", documents=" + this.getDocuments() + ")";
    }
}
