// Generated by delombok at Sat Jun 27 10:20:23 GMT 2026
package com.onmm.backend.dto.Admin;

import java.time.LocalDateTime;
import java.util.List;

public class DashboardStatsResponse {
    private long totalDemandes;
    private long demandesEnAttente;
    private long demandesAcceptees;
    private long demandesRejetees;
    private long totalMedecins;
    private long medecinsActifs;
    private long medecinsSuspendus;
    private long medecinsHommes;
    private long medecinsFemmes;
    private long medecinsMauritaniens;
    private long medecinsEtrangers;
    private long totalSpecialites;
    private long specialitesAvecMedecins;
    private long reclamationsEnAttente;
    private List<RecentDemandeDto> recentDemandes;


    public static class RecentDemandeDto {
        private Long id;
        private String nom;
        private String prenom;
        private String numeroDossier;
        private String statut;
        private LocalDateTime submissionDate;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Long getId() {
            return this.id;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getNom() {
            return this.nom;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getPrenom() {
            return this.prenom;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getNumeroDossier() {
            return this.numeroDossier;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getStatut() {
            return this.statut;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public LocalDateTime getSubmissionDate() {
            return this.submissionDate;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setId(final Long id) {
            this.id = id;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setNom(final String nom) {
            this.nom = nom;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setPrenom(final String prenom) {
            this.prenom = prenom;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setNumeroDossier(final String numeroDossier) {
            this.numeroDossier = numeroDossier;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setStatut(final String statut) {
            this.statut = statut;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setSubmissionDate(final LocalDateTime submissionDate) {
            this.submissionDate = submissionDate;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof DashboardStatsResponse.RecentDemandeDto)) return false;
            final DashboardStatsResponse.RecentDemandeDto other = (DashboardStatsResponse.RecentDemandeDto) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$id = this.getId();
            final java.lang.Object other$id = other.getId();
            if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
            final java.lang.Object this$nom = this.getNom();
            final java.lang.Object other$nom = other.getNom();
            if (this$nom == null ? other$nom != null : !this$nom.equals(other$nom)) return false;
            final java.lang.Object this$prenom = this.getPrenom();
            final java.lang.Object other$prenom = other.getPrenom();
            if (this$prenom == null ? other$prenom != null : !this$prenom.equals(other$prenom)) return false;
            final java.lang.Object this$numeroDossier = this.getNumeroDossier();
            final java.lang.Object other$numeroDossier = other.getNumeroDossier();
            if (this$numeroDossier == null ? other$numeroDossier != null : !this$numeroDossier.equals(other$numeroDossier)) return false;
            final java.lang.Object this$statut = this.getStatut();
            final java.lang.Object other$statut = other.getStatut();
            if (this$statut == null ? other$statut != null : !this$statut.equals(other$statut)) return false;
            final java.lang.Object this$submissionDate = this.getSubmissionDate();
            final java.lang.Object other$submissionDate = other.getSubmissionDate();
            if (this$submissionDate == null ? other$submissionDate != null : !this$submissionDate.equals(other$submissionDate)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof DashboardStatsResponse.RecentDemandeDto;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $id = this.getId();
            result = result * PRIME + ($id == null ? 43 : $id.hashCode());
            final java.lang.Object $nom = this.getNom();
            result = result * PRIME + ($nom == null ? 43 : $nom.hashCode());
            final java.lang.Object $prenom = this.getPrenom();
            result = result * PRIME + ($prenom == null ? 43 : $prenom.hashCode());
            final java.lang.Object $numeroDossier = this.getNumeroDossier();
            result = result * PRIME + ($numeroDossier == null ? 43 : $numeroDossier.hashCode());
            final java.lang.Object $statut = this.getStatut();
            result = result * PRIME + ($statut == null ? 43 : $statut.hashCode());
            final java.lang.Object $submissionDate = this.getSubmissionDate();
            result = result * PRIME + ($submissionDate == null ? 43 : $submissionDate.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "DashboardStatsResponse.RecentDemandeDto(id=" + this.getId() + ", nom=" + this.getNom() + ", prenom=" + this.getPrenom() + ", numeroDossier=" + this.getNumeroDossier() + ", statut=" + this.getStatut() + ", submissionDate=" + this.getSubmissionDate() + ")";
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RecentDemandeDto(final Long id, final String nom, final String prenom, final String numeroDossier, final String statut, final LocalDateTime submissionDate) {
            this.id = id;
            this.nom = nom;
            this.prenom = prenom;
            this.numeroDossier = numeroDossier;
            this.statut = statut;
            this.submissionDate = submissionDate;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RecentDemandeDto() {
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public long getTotalDemandes() {
        return this.totalDemandes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public long getDemandesEnAttente() {
        return this.demandesEnAttente;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public long getDemandesAcceptees() {
        return this.demandesAcceptees;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public long getDemandesRejetees() {
        return this.demandesRejetees;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public long getTotalMedecins() {
        return this.totalMedecins;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public long getMedecinsActifs() {
        return this.medecinsActifs;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public long getMedecinsSuspendus() {
        return this.medecinsSuspendus;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public long getMedecinsHommes() {
        return this.medecinsHommes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public long getMedecinsFemmes() {
        return this.medecinsFemmes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public long getMedecinsMauritaniens() {
        return this.medecinsMauritaniens;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public long getMedecinsEtrangers() {
        return this.medecinsEtrangers;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public long getTotalSpecialites() {
        return this.totalSpecialites;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public long getSpecialitesAvecMedecins() {
        return this.specialitesAvecMedecins;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public long getReclamationsEnAttente() {
        return this.reclamationsEnAttente;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<RecentDemandeDto> getRecentDemandes() {
        return this.recentDemandes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTotalDemandes(final long totalDemandes) {
        this.totalDemandes = totalDemandes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDemandesEnAttente(final long demandesEnAttente) {
        this.demandesEnAttente = demandesEnAttente;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDemandesAcceptees(final long demandesAcceptees) {
        this.demandesAcceptees = demandesAcceptees;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDemandesRejetees(final long demandesRejetees) {
        this.demandesRejetees = demandesRejetees;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTotalMedecins(final long totalMedecins) {
        this.totalMedecins = totalMedecins;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMedecinsActifs(final long medecinsActifs) {
        this.medecinsActifs = medecinsActifs;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMedecinsSuspendus(final long medecinsSuspendus) {
        this.medecinsSuspendus = medecinsSuspendus;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMedecinsHommes(final long medecinsHommes) {
        this.medecinsHommes = medecinsHommes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMedecinsFemmes(final long medecinsFemmes) {
        this.medecinsFemmes = medecinsFemmes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMedecinsMauritaniens(final long medecinsMauritaniens) {
        this.medecinsMauritaniens = medecinsMauritaniens;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMedecinsEtrangers(final long medecinsEtrangers) {
        this.medecinsEtrangers = medecinsEtrangers;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTotalSpecialites(final long totalSpecialites) {
        this.totalSpecialites = totalSpecialites;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSpecialitesAvecMedecins(final long specialitesAvecMedecins) {
        this.specialitesAvecMedecins = specialitesAvecMedecins;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setReclamationsEnAttente(final long reclamationsEnAttente) {
        this.reclamationsEnAttente = reclamationsEnAttente;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRecentDemandes(final List<RecentDemandeDto> recentDemandes) {
        this.recentDemandes = recentDemandes;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof DashboardStatsResponse)) return false;
        final DashboardStatsResponse other = (DashboardStatsResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getTotalDemandes() != other.getTotalDemandes()) return false;
        if (this.getDemandesEnAttente() != other.getDemandesEnAttente()) return false;
        if (this.getDemandesAcceptees() != other.getDemandesAcceptees()) return false;
        if (this.getDemandesRejetees() != other.getDemandesRejetees()) return false;
        if (this.getTotalMedecins() != other.getTotalMedecins()) return false;
        if (this.getMedecinsActifs() != other.getMedecinsActifs()) return false;
        if (this.getMedecinsSuspendus() != other.getMedecinsSuspendus()) return false;
        if (this.getMedecinsHommes() != other.getMedecinsHommes()) return false;
        if (this.getMedecinsFemmes() != other.getMedecinsFemmes()) return false;
        if (this.getMedecinsMauritaniens() != other.getMedecinsMauritaniens()) return false;
        if (this.getMedecinsEtrangers() != other.getMedecinsEtrangers()) return false;
        if (this.getTotalSpecialites() != other.getTotalSpecialites()) return false;
        if (this.getSpecialitesAvecMedecins() != other.getSpecialitesAvecMedecins()) return false;
        if (this.getReclamationsEnAttente() != other.getReclamationsEnAttente()) return false;
        final java.lang.Object this$recentDemandes = this.getRecentDemandes();
        final java.lang.Object other$recentDemandes = other.getRecentDemandes();
        if (this$recentDemandes == null ? other$recentDemandes != null : !this$recentDemandes.equals(other$recentDemandes)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof DashboardStatsResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final long $totalDemandes = this.getTotalDemandes();
        result = result * PRIME + (int) ($totalDemandes >>> 32 ^ $totalDemandes);
        final long $demandesEnAttente = this.getDemandesEnAttente();
        result = result * PRIME + (int) ($demandesEnAttente >>> 32 ^ $demandesEnAttente);
        final long $demandesAcceptees = this.getDemandesAcceptees();
        result = result * PRIME + (int) ($demandesAcceptees >>> 32 ^ $demandesAcceptees);
        final long $demandesRejetees = this.getDemandesRejetees();
        result = result * PRIME + (int) ($demandesRejetees >>> 32 ^ $demandesRejetees);
        final long $totalMedecins = this.getTotalMedecins();
        result = result * PRIME + (int) ($totalMedecins >>> 32 ^ $totalMedecins);
        final long $medecinsActifs = this.getMedecinsActifs();
        result = result * PRIME + (int) ($medecinsActifs >>> 32 ^ $medecinsActifs);
        final long $medecinsSuspendus = this.getMedecinsSuspendus();
        result = result * PRIME + (int) ($medecinsSuspendus >>> 32 ^ $medecinsSuspendus);
        final long $medecinsHommes = this.getMedecinsHommes();
        result = result * PRIME + (int) ($medecinsHommes >>> 32 ^ $medecinsHommes);
        final long $medecinsFemmes = this.getMedecinsFemmes();
        result = result * PRIME + (int) ($medecinsFemmes >>> 32 ^ $medecinsFemmes);
        final long $medecinsMauritaniens = this.getMedecinsMauritaniens();
        result = result * PRIME + (int) ($medecinsMauritaniens >>> 32 ^ $medecinsMauritaniens);
        final long $medecinsEtrangers = this.getMedecinsEtrangers();
        result = result * PRIME + (int) ($medecinsEtrangers >>> 32 ^ $medecinsEtrangers);
        final long $totalSpecialites = this.getTotalSpecialites();
        result = result * PRIME + (int) ($totalSpecialites >>> 32 ^ $totalSpecialites);
        final long $specialitesAvecMedecins = this.getSpecialitesAvecMedecins();
        result = result * PRIME + (int) ($specialitesAvecMedecins >>> 32 ^ $specialitesAvecMedecins);
        final long $reclamationsEnAttente = this.getReclamationsEnAttente();
        result = result * PRIME + (int) ($reclamationsEnAttente >>> 32 ^ $reclamationsEnAttente);
        final java.lang.Object $recentDemandes = this.getRecentDemandes();
        result = result * PRIME + ($recentDemandes == null ? 43 : $recentDemandes.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "DashboardStatsResponse(totalDemandes=" + this.getTotalDemandes() + ", demandesEnAttente=" + this.getDemandesEnAttente() + ", demandesAcceptees=" + this.getDemandesAcceptees() + ", demandesRejetees=" + this.getDemandesRejetees() + ", totalMedecins=" + this.getTotalMedecins() + ", medecinsActifs=" + this.getMedecinsActifs() + ", medecinsSuspendus=" + this.getMedecinsSuspendus() + ", medecinsHommes=" + this.getMedecinsHommes() + ", medecinsFemmes=" + this.getMedecinsFemmes() + ", medecinsMauritaniens=" + this.getMedecinsMauritaniens() + ", medecinsEtrangers=" + this.getMedecinsEtrangers() + ", totalSpecialites=" + this.getTotalSpecialites() + ", specialitesAvecMedecins=" + this.getSpecialitesAvecMedecins() + ", reclamationsEnAttente=" + this.getReclamationsEnAttente() + ", recentDemandes=" + this.getRecentDemandes() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DashboardStatsResponse(final long totalDemandes, final long demandesEnAttente, final long demandesAcceptees, final long demandesRejetees, final long totalMedecins, final long medecinsActifs, final long medecinsSuspendus, final long medecinsHommes, final long medecinsFemmes, final long medecinsMauritaniens, final long medecinsEtrangers, final long totalSpecialites, final long specialitesAvecMedecins, final long reclamationsEnAttente, final List<RecentDemandeDto> recentDemandes) {
        this.totalDemandes = totalDemandes;
        this.demandesEnAttente = demandesEnAttente;
        this.demandesAcceptees = demandesAcceptees;
        this.demandesRejetees = demandesRejetees;
        this.totalMedecins = totalMedecins;
        this.medecinsActifs = medecinsActifs;
        this.medecinsSuspendus = medecinsSuspendus;
        this.medecinsHommes = medecinsHommes;
        this.medecinsFemmes = medecinsFemmes;
        this.medecinsMauritaniens = medecinsMauritaniens;
        this.medecinsEtrangers = medecinsEtrangers;
        this.totalSpecialites = totalSpecialites;
        this.specialitesAvecMedecins = specialitesAvecMedecins;
        this.reclamationsEnAttente = reclamationsEnAttente;
        this.recentDemandes = recentDemandes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DashboardStatsResponse() {
    }
}
