// Generated by delombok at Sat Jun 27 10:20:23 GMT 2026
package com.onmm.backend.dto.Admin;

import jakarta.validation.constraints.NotBlank;

public class RejectRequest {
    @NotBlank(message = "Le motif de rejet est obligatoire")
    private String adminComment;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAdminComment() {
        return this.adminComment;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAdminComment(final String adminComment) {
        this.adminComment = adminComment;
    }
}
