// Generated by delombok at Sat Jun 27 10:20:23 GMT 2026
package com.onmm.backend.dto.Admin;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

public class UpdateAdminProfileRequest {
    @NotBlank(message = "Le nom complet est obligatoire")
    @Size(max = 200, message = "Le nom complet ne peut pas dépasser 200 caractères")
    private String nomComplet;
    private String telephone;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UpdateAdminProfileRequest() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNomComplet() {
        return this.nomComplet;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTelephone() {
        return this.telephone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNomComplet(final String nomComplet) {
        this.nomComplet = nomComplet;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTelephone(final String telephone) {
        this.telephone = telephone;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof UpdateAdminProfileRequest)) return false;
        final UpdateAdminProfileRequest other = (UpdateAdminProfileRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$nomComplet = this.getNomComplet();
        final java.lang.Object other$nomComplet = other.getNomComplet();
        if (this$nomComplet == null ? other$nomComplet != null : !this$nomComplet.equals(other$nomComplet)) return false;
        final java.lang.Object this$telephone = this.getTelephone();
        final java.lang.Object other$telephone = other.getTelephone();
        if (this$telephone == null ? other$telephone != null : !this$telephone.equals(other$telephone)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof UpdateAdminProfileRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $nomComplet = this.getNomComplet();
        result = result * PRIME + ($nomComplet == null ? 43 : $nomComplet.hashCode());
        final java.lang.Object $telephone = this.getTelephone();
        result = result * PRIME + ($telephone == null ? 43 : $telephone.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "UpdateAdminProfileRequest(nomComplet=" + this.getNomComplet() + ", telephone=" + this.getTelephone() + ")";
    }
}
