// Generated by delombok at Sat Jun 27 10:20:23 GMT 2026
package com.onmm.backend.dto;

import com.onmm.backend.entity.enums.*;

public class ContenuDTO {
    private Long id;
    private String titre;
    private String contenu;
    private ContenuType type;
    private ContenuStatut statut;
    private ContenuVisibilite visibilite;
    private Long categorieId;
    private String categorieNom;
    private String createdBy;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTitre() {
        return this.titre;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getContenu() {
        return this.contenu;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ContenuType getType() {
        return this.type;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ContenuStatut getStatut() {
        return this.statut;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ContenuVisibilite getVisibilite() {
        return this.visibilite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getCategorieId() {
        return this.categorieId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCategorieNom() {
        return this.categorieNom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCreatedBy() {
        return this.createdBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTitre(final String titre) {
        this.titre = titre;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setContenu(final String contenu) {
        this.contenu = contenu;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setType(final ContenuType type) {
        this.type = type;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatut(final ContenuStatut statut) {
        this.statut = statut;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVisibilite(final ContenuVisibilite visibilite) {
        this.visibilite = visibilite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategorieId(final Long categorieId) {
        this.categorieId = categorieId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategorieNom(final String categorieNom) {
        this.categorieNom = categorieNom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedBy(final String createdBy) {
        this.createdBy = createdBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ContenuDTO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ContenuDTO(final Long id, final String titre, final String contenu, final ContenuType type, final ContenuStatut statut, final ContenuVisibilite visibilite, final Long categorieId, final String categorieNom, final String createdBy) {
        this.id = id;
        this.titre = titre;
        this.contenu = contenu;
        this.type = type;
        this.statut = statut;
        this.visibilite = visibilite;
        this.categorieId = categorieId;
        this.categorieNom = categorieNom;
        this.createdBy = createdBy;
    }
}
