// Generated by delombok at Sat Jun 27 10:20:23 GMT 2026
package com.onmm.backend.dto;

public class DemandeAdhesionResponse {
    private Long id;
    private String numeroDossier;
    private String statut;
    private String message;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DemandeAdhesionResponse() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNumeroDossier() {
        return this.numeroDossier;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatut() {
        return this.statut;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getMessage() {
        return this.message;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNumeroDossier(final String numeroDossier) {
        this.numeroDossier = numeroDossier;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatut(final String statut) {
        this.statut = statut;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMessage(final String message) {
        this.message = message;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof DemandeAdhesionResponse)) return false;
        final DemandeAdhesionResponse other = (DemandeAdhesionResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$numeroDossier = this.getNumeroDossier();
        final java.lang.Object other$numeroDossier = other.getNumeroDossier();
        if (this$numeroDossier == null ? other$numeroDossier != null : !this$numeroDossier.equals(other$numeroDossier)) return false;
        final java.lang.Object this$statut = this.getStatut();
        final java.lang.Object other$statut = other.getStatut();
        if (this$statut == null ? other$statut != null : !this$statut.equals(other$statut)) return false;
        final java.lang.Object this$message = this.getMessage();
        final java.lang.Object other$message = other.getMessage();
        if (this$message == null ? other$message != null : !this$message.equals(other$message)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof DemandeAdhesionResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $numeroDossier = this.getNumeroDossier();
        result = result * PRIME + ($numeroDossier == null ? 43 : $numeroDossier.hashCode());
        final java.lang.Object $statut = this.getStatut();
        result = result * PRIME + ($statut == null ? 43 : $statut.hashCode());
        final java.lang.Object $message = this.getMessage();
        result = result * PRIME + ($message == null ? 43 : $message.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "DemandeAdhesionResponse(id=" + this.getId() + ", numeroDossier=" + this.getNumeroDossier() + ", statut=" + this.getStatut() + ", message=" + this.getMessage() + ")";
    }
}
