// Generated by delombok at Sat Jun 27 10:20:24 GMT 2026
package com.onmm.backend.dto;

import java.util.List;

public class DemandeCompleteRequest {
    private DemandeAdhesionRequest personal;
    private List<DemandeEducationRequest> education;
    private List<DemandeExperienceRequest> experience;
    private DemandeDocumentRequest documents;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DemandeCompleteRequest() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DemandeAdhesionRequest getPersonal() {
        return this.personal;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<DemandeEducationRequest> getEducation() {
        return this.education;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<DemandeExperienceRequest> getExperience() {
        return this.experience;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DemandeDocumentRequest getDocuments() {
        return this.documents;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPersonal(final DemandeAdhesionRequest personal) {
        this.personal = personal;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEducation(final List<DemandeEducationRequest> education) {
        this.education = education;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setExperience(final List<DemandeExperienceRequest> experience) {
        this.experience = experience;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDocuments(final DemandeDocumentRequest documents) {
        this.documents = documents;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof DemandeCompleteRequest)) return false;
        final DemandeCompleteRequest other = (DemandeCompleteRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$personal = this.getPersonal();
        final java.lang.Object other$personal = other.getPersonal();
        if (this$personal == null ? other$personal != null : !this$personal.equals(other$personal)) return false;
        final java.lang.Object this$education = this.getEducation();
        final java.lang.Object other$education = other.getEducation();
        if (this$education == null ? other$education != null : !this$education.equals(other$education)) return false;
        final java.lang.Object this$experience = this.getExperience();
        final java.lang.Object other$experience = other.getExperience();
        if (this$experience == null ? other$experience != null : !this$experience.equals(other$experience)) return false;
        final java.lang.Object this$documents = this.getDocuments();
        final java.lang.Object other$documents = other.getDocuments();
        if (this$documents == null ? other$documents != null : !this$documents.equals(other$documents)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof DemandeCompleteRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $personal = this.getPersonal();
        result = result * PRIME + ($personal == null ? 43 : $personal.hashCode());
        final java.lang.Object $education = this.getEducation();
        result = result * PRIME + ($education == null ? 43 : $education.hashCode());
        final java.lang.Object $experience = this.getExperience();
        result = result * PRIME + ($experience == null ? 43 : $experience.hashCode());
        final java.lang.Object $documents = this.getDocuments();
        result = result * PRIME + ($documents == null ? 43 : $documents.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "DemandeCompleteRequest(personal=" + this.getPersonal() + ", education=" + this.getEducation() + ", experience=" + this.getExperience() + ", documents=" + this.getDocuments() + ")";
    }
}
