// Generated by delombok at Sat Jun 27 10:20:23 GMT 2026
package com.onmm.backend.dto;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Past;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import java.time.LocalDate;

public class DemandeAdhesionRequest {
    @NotBlank(message = "Le NNI est obligatoire")
    private String nni;
    @NotBlank(message = "Le nom est obligatoire")
    @Size(max = 100, message = "Le nom ne peut pas dépasser 100 caractères")
    private String nom;
    @NotBlank(message = "Le prénom est obligatoire")
    @Size(max = 100, message = "Le prénom ne peut pas dépasser 100 caractères")
    private String prenom;
    @NotBlank(message = "Le sexe est obligatoire")
    private String sexe;
    @NotBlank(message = "La nationalité est obligatoire")
    private String nationalite;
    @NotNull(message = "La date de naissance est obligatoire")
    @Past(message = "La date de naissance doit être dans le passé")
    private LocalDate dateNaissance;
    @NotBlank(message = "L\'email est obligatoire")
    @Email(message = "Format d\'email invalide")
    private String email;
    @NotBlank(message = "Le téléphone est obligatoire")
    @Pattern(regexp = "^[234]\\d{7}$", message = "Format de téléphone mauritanien invalide (8 chiffres commençant par 2, 3 ou 4)")
    private String telephone;
    @NotBlank(message = "L\'adresse est obligatoire")
    private String adresse;
    @NotBlank(message = "La wilaya d\'exercice est obligatoire")
    private String wilayaExercice;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DemandeAdhesionRequest() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNni() {
        return this.nni;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNom() {
        return this.nom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPrenom() {
        return this.prenom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSexe() {
        return this.sexe;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNationalite() {
        return this.nationalite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDate getDateNaissance() {
        return this.dateNaissance;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTelephone() {
        return this.telephone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAdresse() {
        return this.adresse;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getWilayaExercice() {
        return this.wilayaExercice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNni(final String nni) {
        this.nni = nni;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNom(final String nom) {
        this.nom = nom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPrenom(final String prenom) {
        this.prenom = prenom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSexe(final String sexe) {
        this.sexe = sexe;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNationalite(final String nationalite) {
        this.nationalite = nationalite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDateNaissance(final LocalDate dateNaissance) {
        this.dateNaissance = dateNaissance;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTelephone(final String telephone) {
        this.telephone = telephone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAdresse(final String adresse) {
        this.adresse = adresse;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWilayaExercice(final String wilayaExercice) {
        this.wilayaExercice = wilayaExercice;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof DemandeAdhesionRequest)) return false;
        final DemandeAdhesionRequest other = (DemandeAdhesionRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$nni = this.getNni();
        final java.lang.Object other$nni = other.getNni();
        if (this$nni == null ? other$nni != null : !this$nni.equals(other$nni)) return false;
        final java.lang.Object this$nom = this.getNom();
        final java.lang.Object other$nom = other.getNom();
        if (this$nom == null ? other$nom != null : !this$nom.equals(other$nom)) return false;
        final java.lang.Object this$prenom = this.getPrenom();
        final java.lang.Object other$prenom = other.getPrenom();
        if (this$prenom == null ? other$prenom != null : !this$prenom.equals(other$prenom)) return false;
        final java.lang.Object this$sexe = this.getSexe();
        final java.lang.Object other$sexe = other.getSexe();
        if (this$sexe == null ? other$sexe != null : !this$sexe.equals(other$sexe)) return false;
        final java.lang.Object this$nationalite = this.getNationalite();
        final java.lang.Object other$nationalite = other.getNationalite();
        if (this$nationalite == null ? other$nationalite != null : !this$nationalite.equals(other$nationalite)) return false;
        final java.lang.Object this$dateNaissance = this.getDateNaissance();
        final java.lang.Object other$dateNaissance = other.getDateNaissance();
        if (this$dateNaissance == null ? other$dateNaissance != null : !this$dateNaissance.equals(other$dateNaissance)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$telephone = this.getTelephone();
        final java.lang.Object other$telephone = other.getTelephone();
        if (this$telephone == null ? other$telephone != null : !this$telephone.equals(other$telephone)) return false;
        final java.lang.Object this$adresse = this.getAdresse();
        final java.lang.Object other$adresse = other.getAdresse();
        if (this$adresse == null ? other$adresse != null : !this$adresse.equals(other$adresse)) return false;
        final java.lang.Object this$wilayaExercice = this.getWilayaExercice();
        final java.lang.Object other$wilayaExercice = other.getWilayaExercice();
        if (this$wilayaExercice == null ? other$wilayaExercice != null : !this$wilayaExercice.equals(other$wilayaExercice)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof DemandeAdhesionRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $nni = this.getNni();
        result = result * PRIME + ($nni == null ? 43 : $nni.hashCode());
        final java.lang.Object $nom = this.getNom();
        result = result * PRIME + ($nom == null ? 43 : $nom.hashCode());
        final java.lang.Object $prenom = this.getPrenom();
        result = result * PRIME + ($prenom == null ? 43 : $prenom.hashCode());
        final java.lang.Object $sexe = this.getSexe();
        result = result * PRIME + ($sexe == null ? 43 : $sexe.hashCode());
        final java.lang.Object $nationalite = this.getNationalite();
        result = result * PRIME + ($nationalite == null ? 43 : $nationalite.hashCode());
        final java.lang.Object $dateNaissance = this.getDateNaissance();
        result = result * PRIME + ($dateNaissance == null ? 43 : $dateNaissance.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $telephone = this.getTelephone();
        result = result * PRIME + ($telephone == null ? 43 : $telephone.hashCode());
        final java.lang.Object $adresse = this.getAdresse();
        result = result * PRIME + ($adresse == null ? 43 : $adresse.hashCode());
        final java.lang.Object $wilayaExercice = this.getWilayaExercice();
        result = result * PRIME + ($wilayaExercice == null ? 43 : $wilayaExercice.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "DemandeAdhesionRequest(nni=" + this.getNni() + ", nom=" + this.getNom() + ", prenom=" + this.getPrenom() + ", sexe=" + this.getSexe() + ", nationalite=" + this.getNationalite() + ", dateNaissance=" + this.getDateNaissance() + ", email=" + this.getEmail() + ", telephone=" + this.getTelephone() + ", adresse=" + this.getAdresse() + ", wilayaExercice=" + this.getWilayaExercice() + ")";
    }
}
