// Generated by delombok at Sat Jun 27 10:20:24 GMT 2026
package com.onmm.backend.dto;

import java.util.List;

public class DemandeDocumentRequest {
    private List<String> diplomes;
    private List<String> certificats;
    private List<String> autres;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<String> getDiplomes() {
        return this.diplomes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<String> getCertificats() {
        return this.certificats;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<String> getAutres() {
        return this.autres;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDiplomes(final List<String> diplomes) {
        this.diplomes = diplomes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCertificats(final List<String> certificats) {
        this.certificats = certificats;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAutres(final List<String> autres) {
        this.autres = autres;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof DemandeDocumentRequest)) return false;
        final DemandeDocumentRequest other = (DemandeDocumentRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$diplomes = this.getDiplomes();
        final java.lang.Object other$diplomes = other.getDiplomes();
        if (this$diplomes == null ? other$diplomes != null : !this$diplomes.equals(other$diplomes)) return false;
        final java.lang.Object this$certificats = this.getCertificats();
        final java.lang.Object other$certificats = other.getCertificats();
        if (this$certificats == null ? other$certificats != null : !this$certificats.equals(other$certificats)) return false;
        final java.lang.Object this$autres = this.getAutres();
        final java.lang.Object other$autres = other.getAutres();
        if (this$autres == null ? other$autres != null : !this$autres.equals(other$autres)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof DemandeDocumentRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $diplomes = this.getDiplomes();
        result = result * PRIME + ($diplomes == null ? 43 : $diplomes.hashCode());
        final java.lang.Object $certificats = this.getCertificats();
        result = result * PRIME + ($certificats == null ? 43 : $certificats.hashCode());
        final java.lang.Object $autres = this.getAutres();
        result = result * PRIME + ($autres == null ? 43 : $autres.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "DemandeDocumentRequest(diplomes=" + this.getDiplomes() + ", certificats=" + this.getCertificats() + ", autres=" + this.getAutres() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DemandeDocumentRequest() {
    }
}
