// Generated by delombok at Sat Jun 27 10:20:24 GMT 2026
package com.onmm.backend.dto;

import com.onmm.backend.entity.enums.TypeDocument;
import java.time.LocalDateTime;

public class DemandeDocumentResponse {
    private Long id;
    private String typeDocument;
    private String categorie;
    private String fileName;
    private String filePath;
    private Long size;
    private LocalDateTime uploadDate;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DemandeDocumentResponse() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTypeDocument() {
        return this.typeDocument;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCategorie() {
        return this.categorie;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFileName() {
        return this.fileName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFilePath() {
        return this.filePath;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getSize() {
        return this.size;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getUploadDate() {
        return this.uploadDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTypeDocument(final String typeDocument) {
        this.typeDocument = typeDocument;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategorie(final String categorie) {
        this.categorie = categorie;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFileName(final String fileName) {
        this.fileName = fileName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFilePath(final String filePath) {
        this.filePath = filePath;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSize(final Long size) {
        this.size = size;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUploadDate(final LocalDateTime uploadDate) {
        this.uploadDate = uploadDate;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof DemandeDocumentResponse)) return false;
        final DemandeDocumentResponse other = (DemandeDocumentResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$size = this.getSize();
        final java.lang.Object other$size = other.getSize();
        if (this$size == null ? other$size != null : !this$size.equals(other$size)) return false;
        final java.lang.Object this$typeDocument = this.getTypeDocument();
        final java.lang.Object other$typeDocument = other.getTypeDocument();
        if (this$typeDocument == null ? other$typeDocument != null : !this$typeDocument.equals(other$typeDocument)) return false;
        final java.lang.Object this$categorie = this.getCategorie();
        final java.lang.Object other$categorie = other.getCategorie();
        if (this$categorie == null ? other$categorie != null : !this$categorie.equals(other$categorie)) return false;
        final java.lang.Object this$fileName = this.getFileName();
        final java.lang.Object other$fileName = other.getFileName();
        if (this$fileName == null ? other$fileName != null : !this$fileName.equals(other$fileName)) return false;
        final java.lang.Object this$filePath = this.getFilePath();
        final java.lang.Object other$filePath = other.getFilePath();
        if (this$filePath == null ? other$filePath != null : !this$filePath.equals(other$filePath)) return false;
        final java.lang.Object this$uploadDate = this.getUploadDate();
        final java.lang.Object other$uploadDate = other.getUploadDate();
        if (this$uploadDate == null ? other$uploadDate != null : !this$uploadDate.equals(other$uploadDate)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof DemandeDocumentResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $size = this.getSize();
        result = result * PRIME + ($size == null ? 43 : $size.hashCode());
        final java.lang.Object $typeDocument = this.getTypeDocument();
        result = result * PRIME + ($typeDocument == null ? 43 : $typeDocument.hashCode());
        final java.lang.Object $categorie = this.getCategorie();
        result = result * PRIME + ($categorie == null ? 43 : $categorie.hashCode());
        final java.lang.Object $fileName = this.getFileName();
        result = result * PRIME + ($fileName == null ? 43 : $fileName.hashCode());
        final java.lang.Object $filePath = this.getFilePath();
        result = result * PRIME + ($filePath == null ? 43 : $filePath.hashCode());
        final java.lang.Object $uploadDate = this.getUploadDate();
        result = result * PRIME + ($uploadDate == null ? 43 : $uploadDate.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "DemandeDocumentResponse(id=" + this.getId() + ", typeDocument=" + this.getTypeDocument() + ", categorie=" + this.getCategorie() + ", fileName=" + this.getFileName() + ", filePath=" + this.getFilePath() + ", size=" + this.getSize() + ", uploadDate=" + this.getUploadDate() + ")";
    }
}
