spring.application.name=backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/onmm_db
spring.datasource.username=postgres
spring.datasource.password=34509008ma

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

logging.level.org.hibernate.SQL=debug

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mohamedsidimed624@gmail.com
spring.mail.password=xogf vhhr mvtp vvoe

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend-url=http://localhost:5173

upload.dir=uploads

app.sondage.hash-secret=onmm-sondage-secret-dev

#jwt.secret=12345678901234567890123456789012
#jwt.expiration=86400000

#Key key = Keys.secretKeyFor(SignatureAlgorithm.HS256);
#String base64key = Base64.getEncoder().encodeToString(key.getEncoded());
#System.out.println(base64key);