// Generated by delombok at Sat Jun 27 10:20:23 GMT 2026
package com.onmm.backend.dto.contenu;

public class CategorieContenuDTO {
    private Long id;
    private String nom;
    private boolean active;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNom() {
        return this.nom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isActive() {
        return this.active;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNom(final String nom) {
        this.nom = nom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setActive(final boolean active) {
        this.active = active;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CategorieContenuDTO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CategorieContenuDTO(final Long id, final String nom, final boolean active) {
        this.id = id;
        this.nom = nom;
        this.active = active;
    }
}
