// Generated by delombok at Sat Jun 27 10:20:23 GMT 2026
package com.onmm.backend.dto.contenu;

import com.onmm.backend.entity.enums.*;
import jakarta.validation.constraints.NotBlank;

public class ContenuRequestDTO {
    @NotBlank(message = "Le titre est obligatoire")
    private String titre;
    @NotBlank(message = "Le résumé est obligatoire")
    private String resume;
    @NotBlank(message = "Le contenu est obligatoire")
    private String contenu;
    private ContenuType type;
    private ContenuVisibilite visibilite;
    private Long categorieId;
    private String dateExpiration;
    private String description;
    private String imageUrl;
    private Long specialiteCibleId;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTitre() {
        return this.titre;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getResume() {
        return this.resume;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getContenu() {
        return this.contenu;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ContenuType getType() {
        return this.type;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ContenuVisibilite getVisibilite() {
        return this.visibilite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getCategorieId() {
        return this.categorieId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDateExpiration() {
        return this.dateExpiration;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getImageUrl() {
        return this.imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getSpecialiteCibleId() {
        return this.specialiteCibleId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTitre(final String titre) {
        this.titre = titre;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setResume(final String resume) {
        this.resume = resume;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setContenu(final String contenu) {
        this.contenu = contenu;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setType(final ContenuType type) {
        this.type = type;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVisibilite(final ContenuVisibilite visibilite) {
        this.visibilite = visibilite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategorieId(final Long categorieId) {
        this.categorieId = categorieId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDateExpiration(final String dateExpiration) {
        this.dateExpiration = dateExpiration;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setImageUrl(final String imageUrl) {
        this.imageUrl = imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSpecialiteCibleId(final Long specialiteCibleId) {
        this.specialiteCibleId = specialiteCibleId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ContenuRequestDTO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ContenuRequestDTO(final String titre, final String resume, final String contenu, final ContenuType type, final ContenuVisibilite visibilite, final Long categorieId, final String dateExpiration, final String description, final String imageUrl, final Long specialiteCibleId) {
        this.titre = titre;
        this.resume = resume;
        this.contenu = contenu;
        this.type = type;
        this.visibilite = visibilite;
        this.categorieId = categorieId;
        this.dateExpiration = dateExpiration;
        this.description = description;
        this.imageUrl = imageUrl;
        this.specialiteCibleId = specialiteCibleId;
    }
}
