// Generated by delombok at Sat Jun 27 10:20:23 GMT 2026
package com.onmm.backend.dto.contenu;

import com.onmm.backend.entity.enums.*;

public class ContenuResponseDTO {
    private Long id;
    private String titre;
    private String contenu;
    private ContenuType type;
    private ContenuStatut statut;
    private ContenuVisibilite visibilite;
    private Long categorieId;
    private String categorieNom;
    private String createdBy;
    private String dateCreation;
    private String datePublication;
    private String dateExpiration;
    private String imageUrl;
    private String resume;
    private Long specialiteCibleId;
    private String specialiteCibleNom;


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class ContenuResponseDTOBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String titre;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String contenu;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private ContenuType type;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private ContenuStatut statut;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private ContenuVisibilite visibilite;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long categorieId;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String categorieNom;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String createdBy;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String dateCreation;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String datePublication;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String dateExpiration;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String imageUrl;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String resume;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long specialiteCibleId;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String specialiteCibleNom;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        ContenuResponseDTOBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ContenuResponseDTO.ContenuResponseDTOBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ContenuResponseDTO.ContenuResponseDTOBuilder titre(final String titre) {
            this.titre = titre;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ContenuResponseDTO.ContenuResponseDTOBuilder contenu(final String contenu) {
            this.contenu = contenu;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ContenuResponseDTO.ContenuResponseDTOBuilder type(final ContenuType type) {
            this.type = type;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ContenuResponseDTO.ContenuResponseDTOBuilder statut(final ContenuStatut statut) {
            this.statut = statut;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ContenuResponseDTO.ContenuResponseDTOBuilder visibilite(final ContenuVisibilite visibilite) {
            this.visibilite = visibilite;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ContenuResponseDTO.ContenuResponseDTOBuilder categorieId(final Long categorieId) {
            this.categorieId = categorieId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ContenuResponseDTO.ContenuResponseDTOBuilder categorieNom(final String categorieNom) {
            this.categorieNom = categorieNom;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ContenuResponseDTO.ContenuResponseDTOBuilder createdBy(final String createdBy) {
            this.createdBy = createdBy;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ContenuResponseDTO.ContenuResponseDTOBuilder dateCreation(final String dateCreation) {
            this.dateCreation = dateCreation;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ContenuResponseDTO.ContenuResponseDTOBuilder datePublication(final String datePublication) {
            this.datePublication = datePublication;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ContenuResponseDTO.ContenuResponseDTOBuilder dateExpiration(final String dateExpiration) {
            this.dateExpiration = dateExpiration;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ContenuResponseDTO.ContenuResponseDTOBuilder imageUrl(final String imageUrl) {
            this.imageUrl = imageUrl;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ContenuResponseDTO.ContenuResponseDTOBuilder resume(final String resume) {
            this.resume = resume;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ContenuResponseDTO.ContenuResponseDTOBuilder specialiteCibleId(final Long specialiteCibleId) {
            this.specialiteCibleId = specialiteCibleId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ContenuResponseDTO.ContenuResponseDTOBuilder specialiteCibleNom(final String specialiteCibleNom) {
            this.specialiteCibleNom = specialiteCibleNom;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ContenuResponseDTO build() {
            return new ContenuResponseDTO(this.id, this.titre, this.contenu, this.type, this.statut, this.visibilite, this.categorieId, this.categorieNom, this.createdBy, this.dateCreation, this.datePublication, this.dateExpiration, this.imageUrl, this.resume, this.specialiteCibleId, this.specialiteCibleNom);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "ContenuResponseDTO.ContenuResponseDTOBuilder(id=" + this.id + ", titre=" + this.titre + ", contenu=" + this.contenu + ", type=" + this.type + ", statut=" + this.statut + ", visibilite=" + this.visibilite + ", categorieId=" + this.categorieId + ", categorieNom=" + this.categorieNom + ", createdBy=" + this.createdBy + ", dateCreation=" + this.dateCreation + ", datePublication=" + this.datePublication + ", dateExpiration=" + this.dateExpiration + ", imageUrl=" + this.imageUrl + ", resume=" + this.resume + ", specialiteCibleId=" + this.specialiteCibleId + ", specialiteCibleNom=" + this.specialiteCibleNom + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static ContenuResponseDTO.ContenuResponseDTOBuilder builder() {
        return new ContenuResponseDTO.ContenuResponseDTOBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTitre() {
        return this.titre;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getContenu() {
        return this.contenu;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ContenuType getType() {
        return this.type;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ContenuStatut getStatut() {
        return this.statut;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ContenuVisibilite getVisibilite() {
        return this.visibilite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getCategorieId() {
        return this.categorieId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCategorieNom() {
        return this.categorieNom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCreatedBy() {
        return this.createdBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDateCreation() {
        return this.dateCreation;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDatePublication() {
        return this.datePublication;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDateExpiration() {
        return this.dateExpiration;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getImageUrl() {
        return this.imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getResume() {
        return this.resume;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getSpecialiteCibleId() {
        return this.specialiteCibleId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSpecialiteCibleNom() {
        return this.specialiteCibleNom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTitre(final String titre) {
        this.titre = titre;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setContenu(final String contenu) {
        this.contenu = contenu;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setType(final ContenuType type) {
        this.type = type;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatut(final ContenuStatut statut) {
        this.statut = statut;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVisibilite(final ContenuVisibilite visibilite) {
        this.visibilite = visibilite;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategorieId(final Long categorieId) {
        this.categorieId = categorieId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategorieNom(final String categorieNom) {
        this.categorieNom = categorieNom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedBy(final String createdBy) {
        this.createdBy = createdBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDateCreation(final String dateCreation) {
        this.dateCreation = dateCreation;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDatePublication(final String datePublication) {
        this.datePublication = datePublication;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDateExpiration(final String dateExpiration) {
        this.dateExpiration = dateExpiration;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setImageUrl(final String imageUrl) {
        this.imageUrl = imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setResume(final String resume) {
        this.resume = resume;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSpecialiteCibleId(final Long specialiteCibleId) {
        this.specialiteCibleId = specialiteCibleId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSpecialiteCibleNom(final String specialiteCibleNom) {
        this.specialiteCibleNom = specialiteCibleNom;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ContenuResponseDTO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ContenuResponseDTO(final Long id, final String titre, final String contenu, final ContenuType type, final ContenuStatut statut, final ContenuVisibilite visibilite, final Long categorieId, final String categorieNom, final String createdBy, final String dateCreation, final String datePublication, final String dateExpiration, final String imageUrl, final String resume, final Long specialiteCibleId, final String specialiteCibleNom) {
        this.id = id;
        this.titre = titre;
        this.contenu = contenu;
        this.type = type;
        this.statut = statut;
        this.visibilite = visibilite;
        this.categorieId = categorieId;
        this.categorieNom = categorieNom;
        this.createdBy = createdBy;
        this.dateCreation = dateCreation;
        this.datePublication = datePublication;
        this.dateExpiration = dateExpiration;
        this.imageUrl = imageUrl;
        this.resume = resume;
        this.specialiteCibleId = specialiteCibleId;
        this.specialiteCibleNom = specialiteCibleNom;
    }
}
